### ISSUE TITLE
[BUG] Filament change after print ended in max hight forces z-axis to rumble

### ISSUE THREAD

**Issue by schluppy** [prusa3d/Prusa-Firmware-Buddy#963] opened 2020-10-14 09:33 UTC
**Printer type** - [MINI]

**Printer firmware version**-  [4.2.1,]

**Original or Custom firmware** [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive** - [In use]
  
**Describe the bug**
  When the z-axis has stopped at a height of 180 mm during the last press. You can hear an ugly noise of the z-axis when you start the filament change the next time you switch it on.

  When changing the filament the MINI always tries to move the z-axis upwards, even if it is already at the maximum. Also, manually (via the menu) the z-axis cannot be moved down when switching on again.

The only way to avoid the destruction of the motors is to turn the z-axis down by hand on the threaded rod before changing the filament. 

**How to reproduce**
  Move z-axis to maximum height, switch printer off, switch printer on again and perform filament change.

**Expected behavior**
  Query whether the z-axis is at maximum and if the user answers "yes", do not move the z-axis upwards.

**G-code**
  n/a

**Crash dump file**
  n/a

**Video**
  n/a

**Comment by JohnnyDeer** [comment] 2020-10-14 10:30
Hi @schluppy this issue is duplicate of #699. I close this one.

**Closed by JohnnyDeer** 2020-10-14 10:30 UTC
Labels: bug
