### ISSUE TITLE
first layer calibration - wrong temperature

### ISSUE THREAD

**Issue by keksa** [prusa3d/Prusa-Firmware-Buddy#280] opened 2020-03-07 12:15 UTC
FW 4.0.4

The in-built first layer calibration tool is doing mesh bed leveling with nozzle temperature of 215 °C. Since regular prints do mesh bed leveling with nozzle temperature of 170 °C and then wait up for higher temp, I think this might be a bug. 

This also results in random blobs of filament on the bed before the calibration actually starts.

**Comment by Isaac12x** [comment] 2020-04-12 12:50
I think this one is solved with the 4.0.5 update. Can you check?

**Comment by keksa** [comment] 2020-04-26 11:24
Hello @Isaac12x, just updated to 4.0.5 and checked. Nothing changed, still the same behaviour.

**Comment by JohnnyDeer** [comment] 2020-05-05 08:54
Hi @keksa , thank you for reporting, but this issue is already reported. I'm closing this one as duplicate of #157

**Closed by JohnnyDeer** 2020-05-05 08:54 UTC
Labels: duplicate
