### ISSUE TITLE
[FEATURE REQUEST] Remeaning time instead of end print time

### ISSUE THREAD

**Issue by sybaris** [prusa3d/Prusa-Firmware-Buddy#3086] opened 2023-05-27 07:52 UTC
Hi,

**Printer type** : [MINI]

Is it possible to have a settings to display remaning printing time instead of end print time ?
The problem of end print time : 
1°/ You must have a clock or a watch to know the current time, to appreciate when it will be finish
2°/ If the printer si not at the correct time (timezone pb or ntp pb)...

Thanks for advance

Regards
Sybaris

**Comment by cb88** [comment] 2023-06-01 20:34
Time remaining and current layer for example are more useful to me than the existing displayed info. 

Time remaining is actually what shows by default if it isn't networked.

**Comment by reedy** [comment] 2023-06-06 22:59
Dupe of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/648

**Comment by Prusa-Support** [comment] 2023-08-25 13:47
Sorry, this issue should be closed as a duplicate.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-08-25 13:47 UTC
Labels: feature request
