### ISSUE TITLE
[BUG]<differences between Estimated end on Local Connect page and on display >

### ISSUE THREAD

**Issue by drakor007** [prusa3d/Prusa-Firmware-Buddy#758] opened 2020-08-06 11:35 UTC
**Printer type** - [MINI]

**Printer firmware version**-  [ 4.2.0-final ]

**Original or Custom firmware** [Original ]

**Optional upgrades** - [ Filament Runout Sensor ]

**USB drive**
 
**Describe the bug**
  There is a big difference in Estimated end on the display and on Prusa Connect Local page.
  Printer is connected to the Internet, ntp is not blocked.

![PC 2020-08-06 133211](https://user-images.githubusercontent.com/12645375/89527224-4993db80-d7e9-11ea-8237-c2c1bedfafb0.png)
![IMG_20200806_133058](https://user-images.githubusercontent.com/12645375/89527291-603a3280-d7e9-11ea-9cb7-6cfec2d57cfe.jpg)

**Comment by JohnnyDeer** [comment] 2020-08-06 11:39
Hi @drakor007 this issue is duplicate of #708. I´m closing this one.

**Closed by JohnnyDeer** 2020-08-06 11:39 UTC
Labels: bug

**Comment by drakor007** [comment] 2020-08-06 11:41
> Hi @drakor007 this issue is duplicate of #708. I´m closing this one.

OK, I haven´t seen this issue on 4.1. Thank you.
