### ISSUE TITLE
[ENHANCEMENT] Support Filament Motion Sensor

### ISSUE THREAD

**Issue by daterrell** [prusa3d/Prusa-Firmware-Buddy#2208] opened 2022-07-05 00:20 UTC
I have had the Prusa MINI+ for about a year with the stock filament sensor, and I understand its goal is to add as little friction to the filament path as possible, and that filament motion sensors have been developed in the past by Prusa (since discontinued). 

However, having had a number of jams either through poor idler tension or spool knots resulting in lost prints, and cleaning the extruder gears, I would like the option to use a regular encoder gear motion sensor.

I did look into the source code and noticed the default Marlin definition for filament sensor is not used (as well as a separate filament sensor API and specific implementation for the Prusa-style sensor), so merely changing the configuration and using custom firmware is not longer an option :(

**Comment by Prusa-Support** [comment] 2022-08-16 12:11
Thank you for the suggestion.

For the moment, we don't plan to make the firmware compatible with any different filament sensors but the users who want to experiment with other filament sensors can actually make the necessary changes in the firmware because Open Source.
Here you can find the source code and the instructions for the firmware build.
[prusa3d/Prusa-Firmware-Buddy](https://github.com/prusa3d/Prusa-Firmware-Buddy
)
Please be advised that modifying the firmware may be risky and void the warranty. The users can appropriately modify the firmware at their own risk.

Our developers keep on testing alternative solutions and keep on thinking of further improvements for the filament sensor.
This topic was discussed multiple times on the Prusa (i3) Firmware repository.
https://github.com/prusa3d/Prusa-Firmware/issues/476
https://github.com/prusa3d/Prusa-Firmware/issues/505

This issue will be closed as a duplicate of issue #128. Please free to check and comment under the existing issue or please let us know if you think this issue deserves to stay open separately.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2022-08-16 12:11 UTC
Labels: question, feature request, HW issue
