### ISSUE TITLE
[ENHANCEMENT] Use clearer X/Y/Z position icons for footer

### ISSUE THREAD

**Issue by murk-sy** [prusa3d/Prusa-Firmware-Buddy#2546] opened 2022-09-30 11:31 UTC
**Printer type** - [MINI]
**Optional upgrades** - N/A

**Is your suggested improvement related to an existing problem? Please describe.**
Currently the icons are incorrect and can also be confusing, as the coordinate system is actually not as it's displayed by the shape
![image](https://user-images.githubusercontent.com/1211672/193257741-7ccf02b6-5097-47ab-ba46-089321047e6b.png)

**Describe the expected functionality**
I imagine the icons would just be fixed with the correct ones later, but using one of these options would be a lot clearer at a glance, plus having the coordinate system turned correctly would be more intuitive for people unfamiliar with the coordinate system (not that they would then need the numbers?)

The alternative is also to just display the letter in orange - would be clearest for those who need it without any directional ambiguity.

The lowest row is more an experiment of how Y should be displayed, but there's limited space to work with anyway.

![image](https://user-images.githubusercontent.com/1211672/193260566-cab40e5b-ab3e-4f0e-b158-a8598f693975.png)

**Comment by Eldenroot** [comment] 2022-10-23 21:19
Really cool idea, should be changed together alongside with this #2544

**Comment by Prusa-Support** [comment] 2022-11-25 13:54
This issue will be closed as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2544.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2022-11-25 13:54 UTC
Labels: enhancement
