### ISSUE TITLE
[BUG] Screen Blinking on MINI with new firmware 5.1.0 alpha

### ISSUE THREAD

**Issue by xXNoceboXx** [prusa3d/Prusa-Firmware-Buddy#3301] opened 2023-09-22 09:28 UTC
**Printer type** - [MINI]

**Printer firmware version** - [5.1.0-alpha+12820]

**Original or Custom firmware** - [Original]

**USB drive**

**Describe the bug**
  After the launch of the machine, the screen blinking in continue.

**How to reproduce**
  Upgrade Mini with last firmware and launch the machine.

**Expected behavior**
  The screen not blinking.

**Video**
  
https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/3227304/128caf39-1b15-403b-a4b2-62a939e31293

**Comment by CuriousTimo** [comment] 2023-09-22 14:58
Please close. This is a duplicate of issue #3277 
You can add this information to #3277.

Please also post if you are using a Fysect display

**Closed** 2023-09-22 21:01 UTC
Labels: bug
