### ISSUE TITLE
[ENHANCEMENT] Changing filament from PETG to PLA without clogging

### ISSUE THREAD

**Issue by roberto79it** [prusa3d/Prusa-Firmware-Buddy#3027] opened 2023-03-09 08:23 UTC
The idea is that when the filament temperature of the previous material is higher than the current filament, the purging phase is done with the previous filament temperature, so all the residuals in the nozzle are removed with the previous filament temperature.

Usually, when I switch from PETG to PLA, I used this procedure to avoid the nozzle clogging:
- I load PLA filament as PETG, so the nozzle's temperature is enough for melt the PETG residual in the nozzle.
- Purging the filament so I remove all the PETG residual.
- Then I unload and reload the PLA again, so I'm sure that the nozzle is clean and with only PLA inside with the PLA setting.

**Comment by gysnst2** [comment] 2023-03-09 16:06
Actually have to agree with this one also need a load filament and unload filament when octoprint is active!

**Comment by Prusa-Support** [comment] 2023-04-26 14:44
Makes sense. Thank you for your suggestion. 

When a filament is unloaded, it is slightly purged and then withdrawn at the material temperature. This is usually enough but a little residue from the previous material may actually remain.

We already have an open issue about this.
I hope you don't mind me closing this issue as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1821.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-04-26 14:44 UTC
Labels: enhancement, materials, temperature
