### ISSUE TITLE
[BUG] XL moves up during offset calibration.

### ISSUE THREAD

**Issue by dpark12300** [prusa3d/Prusa-Firmware-Buddy#3873] opened 2024-03-30 23:37 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - XL

**Printer firmware version** - 6.0.0 Alpha 1 (5.1.2 works fine)

**Original or Custom firmware** - Original

**Optional upgrades** - 2 Toolheads

**USB drive or USB/Octoprint**
USB
**Describe the bug**
  Printer moves up instead of down during tool offset calibration

**How to reproduce**
  Run tool offset calibration (not dock offset)

**Expected behavior**
  The printer moves down to tap the side of the probe

**G-code**
  No GCODE was loaded during calibration

**Comment by danopernis** [comment] 2024-04-30 17:59
This seems to be a duplicate of #3797 which was fixed in the final version 6.0.0 of the firmware. @dpark12300 can you confirm the issue is no longer present in 6.0.0?

**Comment by dpark12300** [comment] 2024-04-30 18:37
Yes, It seems to be fixed.

**Closed** 2024-04-30 18:42 UTC
Labels: bug, duplicate
