### ISSUE TITLE
Prusalink status isnt updating from previous state to "ready" in home assistant

### ISSUE THREAD

**Issue by Zero-Circle** [prusa3d/Prusa-Firmware-Buddy#4058] opened 2024-06-25 10:32 UTC
### Printer model

MK4

### Firmware version

6.0.2+14873

### Printing from...

Prusa Connect

### Describe the bug

Prusalink status isnt updating from previous state to "ready" in home assistant

### How to reproduce

Set the printer as ready.

### Expected behavior

When printers state changes to ready this should be visable in home assistant

![337939037-c0c09e23-55af-488b-b42d-c06199599df9](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/111734887/1e2a0502-3c5d-4927-866a-a6684b40f54f)

![337939048-34d5aad7-0060-4795-a7b0-82d66cba0ad3](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/111734887/900f9118-000b-43a0-9411-3963191fbcd7)

**Comment by Zero-Circle** [comment] 2024-06-25 10:35
Please note that this issue persists across FW versions 6.0.1, 6.0.2 & 6.0.3

**Comment by danopernis** [comment] 2024-06-25 10:51
What is home assistant? Is this some third party application?

**Comment by 3d-gussner** [comment] 2024-06-25 11:01
@danopernis Home assistant is great home automation platform. https://www.home-assistant.io/

**Comment by 3d-gussner** [comment] 2024-06-25 11:03
@Zero-Circle Please check home assistant plug-in.
I assume that the Ready Not Ready are working correctly in PrusaConnect and PrusaLink but you only have issues with the home assistant plug-in.

**Comment by Zero-Circle** [comment] 2024-06-25 21:24
> @Zero-Circle Please check home assistant plug-in. I assume that the Ready Not Ready are working correctly in PrusaConnect and PrusaLink but you only have issues with the home assistant plug-in. https://www.home-assistant.io/integrations/prusalink/
> 
> In case the PrusaConnect and PrusaLink are working correctly you should close the issue here and open an issue at the home assistant plugin as this a third party product.
> 
> https://github.com/home-assistant/core/tree/dev/homeassistant/components/prusalink
> 
> https://github.com/home-assistant/core/issues?q=is%3Aissue+prusa

Is there a way for a noob to check the raw output of prusalink? SSH or such?

**Comment by 3d-gussner** [comment] 2024-06-26 06:32
@Zero-Circle This is what I have found quickly as I am not that familiar with home assistant yet. https://github.com/home-assistant/core/issues/107242
Hope that helps. Please address your issues in their github repository and close it here.

**Comment by Skaronator** [comment] 2024-06-27 10:54
@Zero-Circle would be better to link the issues the other way around.

@danopernis the issue is that the printer doesn't report the Ready status. It doesn't exist as you can see here: https://github.com/prusa3d/Prusa-Link-Web/blob/ae51b7222c5865f6c796095f8251be05c0fce1f2/spec/openapi.yaml#L1269

I made an issue last year (#3640) requesting this info as well as allow setting the printer READY / NOT_READY.

**Comment by danopernis** [comment] 2024-06-27 11:20
@Skaronator oh good, thank you for the info. I will try to start the company wheels turning, now that I know what is actually being requested :slightly_smiling_face:

**Closed** 2024-06-27 11:22 UTC
Labels: bug, duplicate, third-party

**Comment by RacoJo** [comment] 2025-01-06 18:41
Have you found a way to set the printer ready via HomeAssistant ?
I wanted a easier solution than playing with selenium via a python script
