### ISSUE TITLE
[BUG] MK4 - 5.0.0 stable - Missing translation at the beginning of the print

### ISSUE THREAD

**Issue by Krosta8** [prusa3d/Prusa-Firmware-Buddy#3303] opened 2023-09-22 18:07 UTC
**Printer type** - [MK4]

**Printer firmware version** - [5.0.0 stable]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [None]

**USB drive or USB/Octoprint**
USB via PrusaConnect

**Describe the bug**
If you start the print, it will clear the nozzle, do bed heating and do probing points. These three are not translated. I did not see anything else for now.
I saw similar[ report from MINI](https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2665), so should this be considered as duplicate? It is MK4 vs MINI, FW is the same?
So exact string:
Nozzle Cleaning
Bed Heating
Probing point X/X

**How to reproduce**
Start the print and check the translation at the beginning of the print.

**Expected behavior**
Correct translation

**Comment by danopernis** [comment] 2024-05-30 14:36
Sorry for delay. Yes, this is a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2665

**Closed** 2024-06-27 16:21 UTC
Labels: bug, duplicate
