### ISSUE TITLE
[BFW-5406] [BUG] Nozzle Cleaning Error with 6.0.0

### ISSUE THREAD

**Issue by BillC58** [prusa3d/Prusa-Firmware-Buddy#3818] opened 2024-03-09 01:10 UTC
Printer - XL 5TH

Firmware - 6.0.0

After a week or so printing with the alpha firmware, I started to get a nozzle cleaning error on TH1. 

After a successful print, on the next print job, the printer would try to clean the nozzle with around 50 taps and then fail.

If I reset the printer and reprint, it works fine without any further action from me. It only took 3 or 4 cleaning taps for the printer to continue on.

Then after the successful print, the same nozzle cleaning error occurs on the next print.

I worked with Chat Support and after a few steps, they asked me to downgrade to 5.1.2. This solved the issue.

Chat support has the 8 minute video of this condition.

**Comment by plucker** [comment] 2024-03-31 15:21
Same problem here on two separate machines

**Comment by danopernis** [comment] 2024-04-18 13:43
@bgyarfas @mikelane @alphen87 @shledge @TheYang @BillC58 @brettvitaz @plucker all of you seem to have the same issue, which I am unable to reproduce. So far, it seems that the issue is:
* after successful print, another print fails at the nozzle cleaning stage and it is only fixed by the reset of the printer
* related to 6.0.x series and fixed by reverting to 5.1.x series
* related to multiple printers, including at least XL and MK4

Can we find some similarities shared in all of your cases? Like the nozzle, material, anything else? Is there a minimal gcode to reproduce the issue? For example just `G28` and then `G29 P9`. I would love to fix this issue but I don't have enough data...

**Comment by BillC58** [comment] 2024-04-18 13:53
Dano,

 

I cannot determine a reason for the error.

 

I am using a stock .4 Prusa nozzle in TH1. The error occurs regardless of the material used.

 

I am now in the habit of pressing the reset button after every print to avoid the situation.

 

As a guess, is there something in the memory of the machine from a print that is cleared with a reset? I have a Creality CR-6 that uses a strain gauge. Sometimes, I have to reset that machine to recalibrate the strain gauge.

 

Are there some diagnostics that I can send to you?

 

Bill

**Comment by TheYang** [comment] 2024-04-18 15:25
> @bgyarfas @mikelane @alphen87 @shledge @TheYang @BillC58 @brettvitaz @plucker all of you seem to have the same issue, which I am unable to reproduce. So far, it seems that the issue is:
> 
>     * after successful print, another print fails at the nozzle cleaning stage and it is only fixed by the reset of the printer
> 
>     * related to 6.0.x series and fixed by reverting to 5.1.x series
> 
>     * related to multiple printers, including at least XL and MK4
> 
> 
> Can we find some similarities shared in all of your cases? Like the nozzle, material, anything else? Is there a minimal gcode to reproduce the issue? For example just `G28` and then `G29 P9`. I would love to fix this issue but I don't have enough data...

I have been trying to reproduce the issue for 3 prints now, for now it's working on my 2TH XL.  
After upgrading to 6.0 RC3 on my XL I did have a similar issue once. But it turned out that the Nozzle (V6 Adapter + e3d hardened v6) was loose.  
The nozzle cleaning / bed leveling stage failed, I reset the printer, and it passed, printing the whole model with a bit of leakage, which prompted me to check the nozzle - which was loose.  

I'll have to report back once I got rid of my habit to reset the printer after each print and can reproduce the issue reliably.

**Comment by cplmayo** [comment] 2024-04-18 17:08
I had this error as well and was able to correct however I am now getting a bed leveling error. My assumption is could be related to this considering they both used the loadcell; could totally be wrong. I it would be easier I could open a new issue as I didn't see anything close already; my search foo could have been lacking.

So far to troubleshoot I have washed the build plate, replaced nozzles, and recalibrated everything. Let me know if there is anything else I need to do or can do to help troubleshoot.

**Comment by alphen87** [comment] 2024-04-18 18:04
> @bgyarfas @mikelane @alphen87 @shledge @TheYang @BillC58 @brettvitaz @plucker all of you seem to have the same issue, which I am unable to reproduce. So far, it seems that the issue is:
> 
> * after successful print, another print fails at the nozzle cleaning stage and it is only fixed by the reset of the printer
> * related to 6.0.x series and fixed by reverting to 5.1.x series
> * related to multiple printers, including at least XL and MK4
> 
> Can we find some similarities shared in all of your cases? Like the nozzle, material, anything else? Is there a minimal gcode to reproduce the issue? For example just `G28` and then `G29 P9`. I would love to fix this issue but I don't have enough data...

I tried 3 different tools, all perfect clean .4 brass nozzles and PETG, ASA and PLA filament, and sliced with PS 2.7.4. All jobs have this issue, so i guess there is no specific gcode to reproduce it. Is there some way I can dump/export the memory before and after a print? Perhaps we can find something like a shift in offset?

**Comment by CZDanol** [comment] 2024-04-18 18:40
You guys are lucky (and I am unlucky) :D One of my home printers started doing it, so now we have a reproducer!

**Comment by brettvitaz** [comment] 2024-04-18 22:36
I am on a 5 tool XL: 
- tool: 5
- nozzle: 0.8mm brass
- material: PETG
- firmware: 6.0.0 alpha and 6.0.0 rc3

here is an offending file:
[Cat Spike v3_0.8n_0.3mm_PETG_XLIS_2h39m.bgcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/15031159/Cat.Spike.v3_0.8n_0.3mm_PETG_XLIS_2h39m.bgcode.zip)

Yesterday I did a factory reset on the printer and reflashed rc3 firmware. The problem still exists for that file, but I have had other prints that work properly.

**Comment by bgyarfas** [comment] 2024-04-19 14:04
> @bgyarfas @mikelane @alphen87 @shledge @TheYang @BillC58 @brettvitaz @plucker all of you seem to have the same issue, which I am unable to reproduce. So far, it seems that the issue is:
> 
> * after successful print, another print fails at the nozzle cleaning stage and it is only fixed by the reset of the printer
> * related to 6.0.x series and fixed by reverting to 5.1.x series
> * related to multiple printers, including at least XL and MK4
> 
> Can we find some similarities shared in all of your cases? Like the nozzle, material, anything else? Is there a minimal gcode to reproduce the issue? For example just `G28` and then `G29 P9`. I would love to fix this issue but I don't have enough data...

@danopernis 
> after successful print...
I haven't been able to get a successful print with 6.0.0, it _always_ fails nozzle cleaning

> related to 6.0.x series and fixed by reverting to 5.1.x series
correct

>Can we find some similarities shared in all of your cases? Like the nozzle, material, anything else? 
Prusament PLA, Satin sheet, Official Prusa v6 adapter with a diamondback 0.6 nozzle. I will check everything is tight as I noticed @TheYang mentioned his v6 nozzle was loose. 

On a whim, I monitor the loadcell sensor output on the LCD while the nozzle cleaning was being attempted. On 5.1.x the value appears to peak to approximately -400 while on 6.0.0 it only peaks to -100. It's difficult to see exactly since it's only a single frame at most. Is there a way to log the loadcell sensor output during nozzle cleaning?

I can also try a minimal gcode file that only has the G28 & G90 commands. Do I need any of the preamble that's in a typically generated gcode? I'm assuming I'd also need M17 for instance...

**Comment by cplmayo** [comment] 2024-04-19 16:21
To help diagnose I wanted to share these files:

- [sumo-print-2-11h55m_0.4n_0.25mm_ABS,ABS_XLIS_20h46m.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/15043055/sumo-print-2-11h55m_0.4n_0.25mm_ABS.ABS_XLIS_20h46m.zip)
  - Fails to level or clean the nozzle.
- [knuckle-spikev1_0.4n_0.15mm_ABS,ABS_XLIS_3h16m.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/15043082/knuckle-spikev1_0.4n_0.15mm_ABS.ABS_XLIS_3h16m.zip)
  - Prints without issue

They both are using the same ABS filament profiles loaded in the same toolheads; only difference is size and number of models.

**Comment by BillC58** [comment] 2024-04-21 16:44
I did the following process, which might help identify what is going on.

 

*	Set up a simple cube in Pruseslicer (2.7.4) and sent to my 5 TH XL running 6.0.0 RC3. The cube was 25x25x2 mm.
*	Printed twice in a row on TH1 and the nozzle cleaning failed on the second print.
*	Printed once on TH1, reset the printer and printed again. The nozzle cleaning worked fine.
*	Printed once on TH1, then printed again on TH2 using the filament replacement routine and the second print worked fine.
*	Printed again on TH2, the nozzle cleaning routine worked fine.
*	Printed again on TH1, the nozzle cleaning routine failed.
*	Reset the printer and the same print job worked fine on TH1.

 

My conclusions are:

 

*	The error doesn’t seem to be hardware related as the prints always work fine after a reset.
*	The error does not seem to depend on the model printing or filament used. It happens on the second consecutive print regardless of the model unless a reset is done in between.
*	The error only affects TH1.

 

I don’t know how to print using just G28 and G29 P9. If you send me the complete gcode sample, I can give it a try.

 

Bill

**Comment by shledge** [comment] 2024-04-21 19:35
Just happened to mine just now, on release 6.0. Reset needed to make it work again.

Printing in PLA, stock nozzle probe temps (170c)

**Comment by CZDanol** [comment] 2024-04-23 07:34
Hey guys, we hopefully have a fix, should get out in the next release. It is purely a firmware issue.

**Comment by plucker** [comment] 2024-04-24 23:56
The final version was released - installed it and still getting the error
________________________________

**Comment by cplmayo** [comment] 2024-04-25 01:40
I upgraded to the latest version today; attempted the print that has been giving me problems. Nozzle Clean finished without issue but still reporting a bed leveling error. Should I create a new issue for this?

**Comment by BillC58** [comment] 2024-04-25 02:51
I also still get the nozzle cleaning error with the release version 6.0.0 + 14794.
________________________________

**Comment by shledge** [comment] 2024-04-25 08:08
I noticed it goes away after a while without resetting, but it will happen again on the 2nd print.

Likely an issue with whatever resets/tares the loadcell, leading to it being delayed rather than straight after the previous print?

**Comment by danopernis** [comment] 2024-04-26 10:46
Just to prevent speculations, 6.0.0-RC3 for XL is the same as the final 6.0.0 and as such does not contain any functional changes on top of the 6.0.0-RC3. There are still known issues, including this one. We are working on fixing this, but didn't want to postpone important features like the phase stepping. We will be releasing fix for this issue one we implement it.

To give you some background information, nozzle cleaning error seems to be a timing issue related to analyzing the buffer containing the loadcell samples. On XL the issue seems to be more pronounced, probably due to latency introduced by modbus communication with dwarf daughterboard. Quick fix which should work for most of the cases is to increase the buffer size, but we want to also look at other options for more proper fix.

**Comment by ChrisXLprint** [comment] 2024-05-05 10:48
I have just finished with Prusa support chat, the developers are aware of the bug and are working on it. Currently only able to reslove by reseting printer on the LCD push button or downgrading firmware.

**Comment by einarbey** [comment] 2024-05-06 01:31
do we have some ETA for this bug fix ? i can´t get passed this nozzle cleaning error on my printer. only works if i downgrade to firmware 5.1.3.

**Comment by djcody1** [comment] 2024-05-07 18:50
Same issue on my MK3.9, but can’t get past the error without downgrading to 5.1.3.  Resetting the printer did not fix the issue. Prusa tech support chat is aware.  Itching for the firmware update to drop soon - my MMU3 arrives tomorrow and I’ve already waited so long to use it!

**Comment by SebLaus** [comment] 2024-05-09 10:10
Having the same issue on my MK4.
Since upgrading to 6.00 with MMU3 it does two rows of 15 Calibration taps for nozzle cleaning and then failing. After having contact with Supportchat, we were not able to fix the issue. With 5.1.3 and without MMU3 The printer itself prints fine. But unfortunately not possible with MMU3. With 6.0.0-RC2 it's the same issue.

**Comment by BillC58** [comment] 2024-05-10 19:03
Thanks for the update.

I have the process that if I ever see the print complete screen, I press reset. It’s easy.

Bill
________________________________

**Comment by danopernis** [comment] 2024-05-17 15:40
FYI [v6.0.1](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v6.0.1) was just released, can you please retest? Sorry for all the inconveniences and let's hope the fix works for you :crossed_fingers:

**Comment by I-max-ctrl** [comment] 2024-05-17 20:53
I have a Prusa XL printing ABS on extruder 1 .04 mm nozzle continue to have the same problems as everybody else on the 6.0.0 software once I updated to 6.0.1 it worked once I’m finished with this print. I will let you know how another print goes, glad it wasn’t only happening to m.

**Comment by djcody1** [comment] 2024-05-17 22:13
My MK3.9 is behaving perfectly on 6.0.1 after two prints so far.  Thanks for the quick fix!

**Comment by BillC58** [comment] 2024-05-20 23:54
I was away for a few days. Problem is solved for me.
________________________________

**Comment by CZDanol** [comment] 2024-05-21 08:27
Great, thanks :) Closing the issue then.

**Closed by CZDanol** 2024-05-21 08:27 UTC
Labels: bug, solved, known issue

**Comment by brettvitaz** [comment] 2024-06-19 18:21
I have just experienced this again, with the latest firmware. It has been working well until today when the nozzle cleaning failed and I had to reset the printer to start a new print.

**Comment by CZDanol** [comment] 2024-06-20 07:15
@brettvitaz is it now happening less, or did the update do nothing for you?

**Comment by brettvitaz** [comment] 2024-06-20 18:11
It is happening much less. This is the first time it has happened since the fix.

**Comment by Prusa-Support** [comment] 2024-07-13 14:30
In that case, I'm afraid we are not talking about the issue at firmware level originally discussed in this thread.

Here is a brief list of possible causes of the problem (_non_-firmware related).
- loose nozzle (or incorrectly positioned)
- debris between sheet and bed
- tense/pulled filament (friction opposing the filament unwinding)
- external resonation (e.g. vibrations from other operating devices, people/pets moving around...)
- loose/wobbly bed (or expansion joints, or bearings, or bars)
- noticeably dirty nozzle
- partially clogged nozzle (especially after using high-temp materials)
- inaccurate XYZ movements...
- deformed, too loose, or too tense extruder assembly...
- other "external" causes of the problem... (including problems based on the specific print, or filament...)

This list may not tell much without proper guidance so please contact our [Customer Support](https://help.prusa3d.com/article/customer-support_2287) to get adequate help.

Michele Moramarco
Prusa Research

**Comment by brettvitaz** [comment] 2024-07-15 14:49
While some of these factors this may be true, the issue was solved by restarting the printer. This tells me that there is something wrong in the firmware level. I will attempt to reproduce it since the conditions were largely different from my normal prints (0.8 mm nozzle, using spool join).

**Comment by mgrn0** [comment] 2024-08-08 10:15
I also do still have nozzle cleaning issues with my mk4, will try to reproduce (or eliminate it), hopefully..
