### ISSUE TITLE
[BUG] Crash while printing after 10-30min due thermistor fail shows no descriptive error 

### ISSUE THREAD

**Issue by nachtschatt3n** [prusa3d/Prusa-Firmware-Buddy#1227] opened 2021-01-12 12:38 UTC
**Printer type** - [MINI]

**Printer firmware version**-  [4.3.0 RC1 2691]

**Original or Custom firmware** [Original]

**Optional upgrades** - [none]

**Octoprint** - Version 1.5.2 - Version 0.17.0, running on Raspberry Pi 3 Model B Rev 1.2

**Describe the bug**
Crash and bluescreen, the printer is unresponsive and beeps. Check screenshot

**How to reproduce**
I send the gcode of my model to octoprint via PrusaSlicer 2.3.0+win64 and after 10-30min the printer crashes with a bluescreen. 

**G-code**
[assortment box 3x3 square_0.15mm_PLA_MINI_5h42m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5802076/assortment.box.3x3.square_0.15mm_PLA_MINI_5h42m.gcode.zip)

**Crash dump file**
[dump.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5802146/dump.zip)

![138156862_10207793470870678_2023554667431508633_n](https://user-images.githubusercontent.com/437839/104315020-9ab3a400-54da-11eb-8cac-9f7e859a58ca.jpg)

**Comment by nachtschatt3n** [comment] 2021-01-12 15:10
I downgraded and tried again and now I get a MINITEMP error. Its a broken thermistor and the error message cloud be a little more descriptive

**Comment by JohnnyDeer** [comment] 2021-01-18 09:28
Hi @nachtschatt3n, thank you for reporting. We are working on this issue.

**Comment by JohnnyDeer** [comment] 2021-02-22 07:42
@nachtschatt3n could you please try test this issue on 4.3.1? Printing via USB should be fixed, if you are using OctoPrint there we still did not found reason. Thank you

**Comment by nachtschatt3n** [comment] 2021-02-22 14:37
@JohnnyDeer sorry I already replaced the thermistor and had no issues any more so far. Maybe someone else can try? It only appears with a broken bed thermistor

**Comment by JohnnyDeer** [comment] 2021-02-22 14:50
@nachtschatt3n that's ok, BSOD while printing via OctoPrint caused by broken thermistor cable is know bug. Then I will close this issue. Thank you for update.

**Closed by JohnnyDeer** 2021-02-22 14:50 UTC
Labels: bug
