### ISSUE TITLE
[FEATURE REQUEST] Stealth Mode

### ISSUE THREAD

**Issue by nick8596** [prusa3d/Prusa-Firmware-Buddy#1516] opened 2021-07-28 08:32 UTC
Please add stealth mode for the Prusa mini(+) like we know it from the i3mk3s. This would be a great improvement, the TMC2209 from the Buddy board are very quiet in the StealthChop mode.

**Printer type** - [MINI+]

**Comment by Gordontgopher** [comment] 2021-07-28 17:42
duplicate of #1236

**Closed** 2021-08-02 05:29 UTC
Labels: duplicate, feature request
