### ISSUE TITLE
[BUG] Display rendering breaks

### ISSUE THREAD

**Issue by murk-sy** [prusa3d/Prusa-Firmware-Buddy#1455] opened 2021-06-06 13:58 UTC
**Printer type** - MINI+

**Printer firmware version** -  4.3.2-RC1+2775

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**Describe the bug**
![image](https://user-images.githubusercontent.com/1211672/120926964-6b970c80-c6df-11eb-8c07-87ecbfd3bade.png)

**How to reproduce**
Happened during an overnight print, so no idea. Same gcode was run twice, this was maybe the third time in a row, I assume gcode itself is unrelated. Print finished successfully and the printer appears to work fine.

**Crash dump file**
No crash, printer functioned, see video

**Video**
https://youtu.be/cK57a0TKJYw

**Comment by JohnnyDeer** [comment] 2021-06-07 04:39
Hi @murk-sy, this is duplicate of #1200. I´m closing this issue.

**Closed by JohnnyDeer** 2021-06-07 04:39 UTC
Labels: bug
