### ISSUE TITLE
[ENHANCEMENT] Download binary file locations needs to be more prominent.

### ISSUE THREAD

**Issue by ddirector51** [prusa3d/Prusa-Firmware-Buddy#2372] opened 2022-08-08 13:50 UTC
**Printer type** - [MINI]
**Optional upgrades** - [Documentation improvement]

**Is your suggested improvement related to an existing problem? Please describe.**
I had a great deal of trouble finding the download link for the beta version.

**Describe the expected functionality**
Perhaps a note at the top of the README indicating links are in the assets section at the bottom.

**Comment by Prusa-Support** [comment] 2022-08-18 10:42
Thank you for your feedback.

We will consider your suggestion but please mid this is a peculiarity of the GitHub community.
Please notice that GitHub has its own [GitHub space](github.com/github), where you may report suggestions to improve the website.

On our side, in order to help people who are not familiar with GitHub, we have articles in our Help section. We may improve current articles or create new ones based on the feedback we get.

I'm collecting your feedback and taking notes.
I'll report to both, our developers for possibly more clarity on the release notes, and our content team to improve our own Help documentation.

Because the issue is not related to the _MINI firmware_, I will close it now.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2022-08-18 10:42 UTC
Labels: enhancement
