### ISSUE TITLE
[FEATURE REQUEST] Do not heat up bed on filament change; optionally or by default

### ISSUE THREAD

**Issue by RichiH** [prusa3d/Prusa-Firmware-Buddy#1242] opened 2021-01-18 21:33 UTC
Unloading and loading new filament heats the bed; this is meant to speed up printing right after the change as per https://twitter.com/Prusa3D/status/1351266650931294214

However, I remote print from Octoprint, or maybe Prusa Connect soon, and usually clean the sheet with IPA when I change filaments. Printing happens minutes or hours after I changed the filament. That means I would prefer if the bed didn't heat, or stay heated after the change. It wastes power, means I can burn myself, the filament extruded on change sticks to the bed, and I need to take the sheet off of the printer while it's hot when cleaning with IPA.

I am not sure about what the default should be, but I would like to have a setting to choose behavior if possible.

**Comment by JohnnyDeer** [comment] 2021-01-19 08:09
Hi @RichiH this issue is duplicate of #706. I´m closing this one.

**Closed by JohnnyDeer** 2021-01-19 08:09 UTC
Labels: feature request
