### ISSUE TITLE
[BUG] Printer heats bed when loading or unloading filament - not needed, wastes time and energy

### ISSUE THREAD

**Issue by Gyrxiur** [prusa3d/Prusa-Firmware-Buddy#867] opened 2020-09-05 10:37 UTC
**Printer type** - [MINI]

**Printer firmware version** - 4.2.1

**Original or Custom firmware** - Original

**Describe the bug**
Printer heats bed when loading or unloading filament - it is not needed and it wastes time and energy

**Expected behavior**
Only hotends heats up when changing filament

**Comment by derenma** [comment] 2020-09-10 05:36
I am for, and against, this.

One simple reason: If I am changing filament, I am getting ready to print. However, this is not always the case and I just need to change the filament.

The timeouts are working out well in this regard.

**Comment by JohnnyDeer** [comment] 2020-09-10 07:01
Hi @Gyrxiur this issue is duplicate of #706. I´m closing this one.

**Closed by JohnnyDeer** 2020-09-10 07:01 UTC
Labels: bug
