### ISSUE TITLE
[BFW-5957] [BUG] WiFi 'link down' regression

### ISSUE THREAD

**Issue by flynny75** [prusa3d/Prusa-Firmware-Buddy#4199] opened 2024-09-11 14:50 UTC
### Printer model

XL 5TH

### Firmware version

6.2.0 alpha 1

### Printing from...

N/A

### Describe the bug

WiFi fails to connect, network status just shows 'link down'. I have tried entering the credentials manually with no effect. Searching for networks in the WiFi wizard finds no networks. Printer is physically fine, was working on 6.1.3

**Comment by RPospisil** [comment] 2024-09-11 19:39
Having the same issue on XL. Wifi connection is unstable - on wifi status page I see 100% ping loss mostly. 
Rarely wifi looks like connected, pings looks ok, but printer is offline in prusa connect.
I downgraded to 6.1.3 and wifi works.

**Comment by liyanage** [comment] 2024-09-13 04:30
I'm seeing the same, installed 6.2.0 alpha 1 on my XL 5T today and WiFi no longer works. I see two failure modes:

* The network status either says "Link Down" as mentioned above, or "No AP"
* When I am in that first state, I can power cycle the machine and it will connect, including acquiring the IP address via DHCP, and it will properly resolve buddy-a.connect.prusa.com to an IP address. However, even in this state, it will not be reachable on the network. Ping from another host on the same network just goes nowhere.

As a workaround, I had to connect an Ethernet cable.

**Comment by fogarasia** [comment] 2024-09-13 14:25
I have the same problem, WIFI drop down. The previous version worked well.

**Comment by VibroAxe** [comment] 2024-09-14 21:05
I'm also experiencing this. Possibly related to https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/4200

**Comment by LizPh** [comment] 2024-09-15 15:26
same

**Comment by danopernis** [comment] 2024-09-16 09:01
Thanks for reporting, we are aware of the issue and we are tracking this internally as BFW-5957

**Comment by VibroAxe** [comment] 2024-09-16 18:05
> Thanks for reporting, we are aware of the issue and we are tracking this internally as BFW-5957

Great, any diagnostics we can usefully collect?

**Comment by danopernis** [comment] 2024-09-16 18:27
Not really, but thanks. Just to provide some context:

There have been several changes to Wi-Fi subsystem and all of them were supposed to improve the performance, but it turned out they actually worsen it in some cases. As a hotfix, we are going to revert all of these changes and keep Wi-Fi as it was in previous versions.

Changes involved updating ESP SDK to newest version, rewrite of the parser for the protocol used to communicate with ESP and CRC check for said protocol. We will try applying these changes separately to better understand which of them causes this regression.

**Comment by kchristensen** [comment] 2024-09-25 15:34
Also experiencing weirdness with regards to WiFi -- Is there a way to "unset" WiFi credentials w/o a settings reset? I've wired my printers and would prefer to just "forget" the WiFi settings but I haven't figured out how to do so.

**Comment by mikelane** [comment] 2024-09-29 18:31
Experienced this today as well.

**Comment by danopernis** [comment] 2024-10-01 12:12
Hi folks, v6.2.0-alpha2 just got released which contains the revert of the Wi-Fi changes. You might want to re-test this.

**Comment by ethanrae** [comment] 2024-11-05 07:47
Wi-Fi is working for me again in v6.2.0-alpha2

**Comment by CZDanol** [comment] 2024-11-05 08:19
Closing as done.

**Closed by CZDanol** 2024-11-05 08:19 UTC
Labels: bug, known issue
