### ISSUE TITLE
[FEATURE REQUEST] <Nozzle Cleaning after Color Change>

### ISSUE THREAD

**Issue by smaexmaex** [prusa3d/Prusa-Firmware-Buddy#3139] opened 2023-07-14 13:44 UTC
Printer type - Prusa Mk 4

After I change a color and continue printing, the nozzle is not cleaned again, so a bit of filament that is not sticking out is printed into the print.

Please create that the nozzle is automatically cleaned again, so that the print does not print the excess filament into the print.

**Comment by Prusa-Support** [comment] 2023-10-05 23:05
Thanks for reporting, however, it seems that this issue can be closed as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3139.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-10-05 23:05 UTC
Labels: feature request
