### ISSUE TITLE
[ENHANCEMENT] Actual time when printing

### ISSUE THREAD

**Issue by ThomasCZ** [prusa3d/Prusa-Firmware-Buddy#2663] opened 2022-10-27 22:18 UTC
The printer is showing time of complete instead of remaining time when is connected to WiFi. I think, there is also very important to know the actual time. Could you please show it somewhere (maybe like an option in footer?) or add option to choose remaining time and time of complete?

Thanks

**Comment by Eldenroot** [comment] 2022-10-28 17:31
![IMG_20221028_154623](https://user-images.githubusercontent.com/778890/198697601-5911e517-ac66-4bd7-a206-07cbe03ff4e4.jpg)

**Comment by espr14** [comment] 2023-12-18 14:29
### Like in [Snake FW](https://github.com/Snake-FW/P32-FW/releases)?

![IMG_20231217_223557](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/46957311/24e976c2-34f3-4cd3-94ed-785584a47cc1)

**Comment by Prusa-Support** [comment] 2024-01-17 21:21
This issue will be closed as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/648 and https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1322.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2024-01-17 21:21 UTC
Labels: enhancement
