### ISSUE TITLE
Display flashing/weirdly refeshing in the filament loading menu

### ISSUE THREAD

**Issue by BenHartwich2005** [prusa3d/Prusa-Firmware-Buddy#2320] opened 2022-07-29 13:15 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MINI+

**Printer firmware version** - 4.4.0-BETA2

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint**
  USB Drive

**Describe the bug**
  When changing the Filament the LCD starts flashing weirdly when it res

**How to reproduce**
  Just change the Filament mine was PETG 

**Expected behavior**
  Should work normally without the weird refreshing

https://user-images.githubusercontent.com/77836725/181768243-05ed1e11-fa46-4f4c-be82-1afe8d4690d9.mov

**Comment by tafelberg** [comment] 2022-07-29 15:57
I have the same problem.

**Comment by rbronco21** [comment] 2022-07-29 23:51
> I have the same problem.

👍 
I wanted a reaction thumbs up, but I can't get it to work, so you get a reply.

**Comment by prochazkaml** [comment] 2022-07-30 17:27
Same problem. It starts blinking when it asks me whether the filament unload was successful, keeps blinking throughout the entire loading process (including filament selection), it finally stops blinking when it displays "Loading to nozzle".

One strange thing (not sure whether it is a feature or a bug) was that when (un)loading the filament, it rammed and then immediately started pulling the filament out. In the older releases, there was a short pause between the two.

Also, when I select "Retry" after the filament had been loaded, the screen does not flash at all throughout the process and it works fine. The proper pause is now also present between ramming and unloading stages, as was with earlier releases.

**Comment by Emanuelgtxf** [comment] 2022-07-31 14:49
EU TIVE O MESMO PROBELEMA ...

**Comment by JohnnyDeer** [comment] 2022-08-01 07:01
This issue is duplicate of #2299. I´m closing this one.

**Closed by JohnnyDeer** 2022-08-01 07:01 UTC
Labels: bug
