### ISSUE TITLE
Mesh bed leveling 7x7 (MINI+)

### ISSUE THREAD

**Issue by VladimirVecera** [prusa3d/Prusa-Firmware-Buddy#3088] opened 2023-05-28 07:45 UTC
I couldn't find a better mesh leveling setting anywhere in the printer settings. I wanted to set the printer to 7x7 dots, but I can't see it anywhere in the settings. Is there a possibility to have a better mesh bed leveling setting for the MINI+ printer as well?

**Comment by mix579** [comment] 2023-05-28 12:49
There's no 7x7 MBL on the Mini, only the Mk3S. The Mini only has 4 x 4 due to the smaller bed size. 

You can close this issue.

**Comment by murk-sy** [comment] 2023-06-08 15:00
Duplicate of #1264 
There's also Prusa Support's reply there regarding this

**Comment by Prusa-Support** [comment] 2023-06-16 09:21
Hello, thank you for the request and thank you @murk-sy for pointing to the duplicate issue with our response - closing this particular thread being it a duplicate, but feel free to add any comments to the original thread #1264 

Alessandro Pantaleo
Prusa Research

**Closed by Prusa-Support** 2023-06-16 09:21 UTC
Labels: enhancement
