### ISSUE TITLE
[BUG] Squeaking noise on Y Axis after upgrade to 4.4.0

### ISSUE THREAD

**Issue by urbiworx** [prusa3d/Prusa-Firmware-Buddy#2566] opened 2022-10-04 20:07 UTC
**Printer type** - MINI

**Printer firmware version** - 4.4.0

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Sensor, revo hotend, Bondtech extruder

**USB drive or USB/Octoprint**
 USB Drive

**Describe the bug**
  After upgrade I get a squeaking noise on the y axis before the print starts. It looks like the bed is being pushed a bit more than possible.

**How to reproduce**
  Print with 4.4.0 on my printer

**Expected behavior**
 No noise
**G-code**
  Reproducible with any g code I produced

**Crash dump file**
 No dump file

**Video**
  If it is unclear I will be happy to make one.

**Comment by Prusa-Support** [comment] 2022-10-13 13:31
Thank you for the report.

If the printer is using custom firmware, we may not be able to reproduce the issue and find a solution. If this is the case, please consider closing this issue and reaching the author of the modified firmware about this.

For now though, we can't exclude problems related to hardware or assembly. A video will surely be of help to see what exactly the problem looks like and possibly to understand the root cause of it.

Michele Moramarco
Prusa Research

**Comment by urbiworx** [comment] 2022-10-19 18:52
Hi,

I have used the RC1 firmware provided by prusa. No custom firmware. Here is the video: https://we.tl/t-4wTZiwMuGR

________________________________
Von: Prusa-Support ***@***.***>
Gesendet: Donnerstag, 13. Oktober 2022 15:31
An: prusa3d/Prusa-Firmware-Buddy ***@***.***>
Cc: ***@***.*** ***@***.***>; Author ***@***.***>
Betreff: [SUSPECT] Re: [prusa3d/Prusa-Firmware-Buddy] [BUG] Squeaking noise on Y Axis after upgrade to 4.4.0 (Issue #2566) after upgrade to 4.4.0 (Issue #2566)


Thank you for the report.

If the printer is using custom firmware, we may not be able to reproduce the issue and find a solution. If this is the case, please consider closing this issue and reaching the author of the modified firmware about this.

For now though, we can't exclude problems related to hardware or assembly. A video will surely be of help to see what exactly the problem looks like and possibly to understand the root cause of it.

Michele Moramarco
Prusa Research

**Comment by urbiworx** [comment] 2022-10-21 19:38
[Powerful Blorr (23)_0.2mm_PLA_MINI_28m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/9841989/Powerful.Blorr.23._0.2mm_PLA_MINI_28m.gcode.zip)
Here is an example gcode producing the problem

**Comment by urbiworx** [comment] 2022-10-23 21:29
It was an assembly error. Can be closed.

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Marcel Urbanek ***@***.***>
Gesendet: Wednesday, October 19, 2022 8:52:04 PM
An: prusa3d/Prusa-Firmware-Buddy ***@***.***>
Betreff: AW: [SUSPECT] Re: [prusa3d/Prusa-Firmware-Buddy] [BUG] Squeaking noise on Y Axis after upgrade to 4.4.0 (Issue #2566) after upgrade to 4.4.0 (Issue #2566)

Hi,

I have used the RC1 firmware provided by prusa. No custom firmware. Here is the video: https://we.tl/t-4wTZiwMuGR

________________________________
Von: Prusa-Support ***@***.***>
Gesendet: Donnerstag, 13. Oktober 2022 15:31
An: prusa3d/Prusa-Firmware-Buddy ***@***.***>
Cc: ***@***.*** ***@***.***>; Author ***@***.***>
Betreff: [SUSPECT] Re: [prusa3d/Prusa-Firmware-Buddy] [BUG] Squeaking noise on Y Axis after upgrade to 4.4.0 (Issue #2566) after upgrade to 4.4.0 (Issue #2566)


Thank you for the report.

If the printer is using custom firmware, we may not be able to reproduce the issue and find a solution. If this is the case, please consider closing this issue and reaching the author of the modified firmware about this.

For now though, we can't exclude problems related to hardware or assembly. A video will surely be of help to see what exactly the problem looks like and possibly to understand the root cause of it.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment] 2022-10-29 16:37
Thank you, we appreciate your feedback.

**Closed by Prusa-Support** 2022-10-29 16:37 UTC
Labels: bug, awaiting response, unable to reproduce, troubleshooting
