### ISSUE TITLE
[FEATURE REQUEST] Automated USB Drive Cleanup

### ISSUE THREAD

**Issue by chrishilbert** [prusa3d/Prusa-Firmware-Buddy#3040] opened 2023-03-21 15:55 UTC
**Printer type** - [MINI]

**Describe the expected functionality**
Requesting a feature to run cleanup on the USB drive at some interval.  For example, delete files > 30 days old every night at 1am.  Would be nice to delete files I printed 1 time and never again.  I personally would run it nightly to delete everything so Prusa Slicer doesn't error out on duplicated files.

**Comment by Prusa-Support** [comment] 2023-04-27 17:27
Thanks for your suggestion.

This issue can be closed as a duplicate of https://github.com/prusa3d/Prusa-Link-Web/issues/251.

Based on the average use, it may take several months to fill a rather cheap 8-16 GB flash drive - maybe over one year in the case of a 32GB flash drive.
Our developers will look into this. Fortunately, for the time being, an average user won't need to delete files frequently.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-04-27 17:27 UTC
Labels: feature request
