### ISSUE TITLE
[BFW-5518] [FEATURE REQUEST] MK3.5 To Show Sheet Profile in Footer UI

### ISSUE THREAD

**Issue by Sainx47** [prusa3d/Prusa-Firmware-Buddy#3850] opened 2024-03-22 16:26 UTC
**Printer type** - [MK3.5]
**Optional upgrades** - [Steel Sheet Profile in Footer UI]

**Is your suggested improvement related to an existing problem? Please describe.**

Feature Request for MK3.5

1. Steel Sheet Profile on the Footer UI.
2. Renaming steel sheet profiles.

**Describe the expected functionality**
The ability to have an option to choose "Steel Sheet Profile" as a UI item to be shown in the footer.

Currently the selected steel sheet is hidden behind the control menu. Someone could easily forget which sheet is selected and print on a different one causing first layer issues. Having it shown in the footer will prevent such issues, that will lead to inaccurate z offset and failed prints.

Also, there is no option named Satin. only Smooth 1 & 2, Textured 1  & 2, Custom 1 to 4.

It would be great to rename the custom to something like PET Carbon. Or at least have Satin and PA Nylon sheet just like MK3S+

**Comment by maxkueng** [comment] 2024-03-23 03:11
Duplicate of #3789?

**Comment by kajeq** [comment] 2024-03-26 17:40
I second this feature request. This would be a big improvement.

**Comment by ChrisHeerschap** [comment] 2024-03-27 19:50
Not a duplicate of 3789 that's just adding the sheet name to the footer, which is a great idea, but I also really want the ability to rename sheets. Had it in the MK3 and used it and assumed it was there in the MK35 only to discover it's not there.

**Comment by tomekmgr** [comment] 2024-04-05 18:52
I'm just finished with an update and after initial run I realize that this feature is missing. 
You can do it, but too deep in menu. Having info and change option on main screen - please add this.

**Comment by kvtorp** [comment] 2024-04-07 22:40
I have been looking around for it, but there seems to be no way of knowing which sheet is currently selected. This is a necessary feature!

**Comment by anderl1969** [comment] 2024-05-06 12:28
I second this too. After upgrading to 3.5 yesterday, I already missing this feature a lot!

**Comment by LukeShootsThings** [comment] 2024-05-12 15:32
Commenting to show support for adding this functionality.  I have a MK3.5 and would love to be able to see which sheet profile is selected right from the footer.

**Comment by CZDanol** [comment] 2024-05-16 14:58
Hey, closing as a duplicate of #3789 . This doesn't mean we won't do this, we're only aggregating issues that are about the same thing.

**Closed by CZDanol** 2024-05-16 14:58 UTC
Labels: duplicate, feature request

**Comment by IanAdd** [comment] 2024-07-29 02:24
Awfully, confused here. This issue, well two enhancement requests, are titled as reuests for the Mk3.5. This suits me. It seems to have been consolidated into #3789 which does not mention Mk3.5, only mini, Mk3.9 and Mk4.

In truth this is a bug/oversight by the developers since the Mk3.5 is an UPGRADE from the Mk3 which had the rename feature.

**Comment by CZDanol** [comment] 2024-07-29 07:27
@IanAdd I don't get it, the #3789 mentions Mk3.5 on multiple places. And Mk4 and Mk3.9 do not have sheet profiles, Anyway, don't worry, all our printers share a firmware platform, so when we implement it, it will be implemented anywhere.

**Comment by IanAdd** [comment] 2024-07-29 07:33
> @IanAdd I don't get it, the #3789 mentions Mk3.5 on multiple places. And Mk4 and Mk3.9 do not have sheet profiles, Anyway, don't worry, all our printers share a firmware platform, so when we implement it, it will be implemented anywhere.

Thanks, It was the link to github when you click on 'scheduled' that left me concerned.

Any idea of a date of release of updates?

**Comment by CZDanol** [comment] 2024-07-29 08:16
> > @IanAdd I don't get it, the #3789 mentions Mk3.5 on multiple places. And Mk4 and Mk3.9 do not have sheet profiles, Anyway, don't worry, all our printers share a firmware platform, so when we implement it, it will be implemented anywhere.
> 
> Thanks, It was the link to github when you click on 'scheduled' that left me concerned.
> 
> Any idea of a date of release of updates?

It should get out on the next non-patch release. I'm not at liberty to share dates though, sorry.
