### ISSUE TITLE
[BUG] Filament sensor still doesn't work over serial/octoprint

### ISSUE THREAD

**Issue by coaxial** [prusa3d/Prusa-Firmware-Buddy#1892] opened 2022-02-22 13:50 UTC
**Printer type**
  MINI

**Printer firmware version**
  4.3.3 and 4.3.4

**Original or Custom firmware**
  Original

**Optional upgrades**
  Filament Runout Sensor

**USB drive or USB/Octoprint**
  Octoprint

**Describe the bug**
  The filament runout sensor still doesn't do anything when it triggers while printing a model with Octoprint. Same as #739.

**How to reproduce**
  1. Turn printer on
  2. On the printer's menu, go to the load or change filament screen
  3. Load the filament as per the prompts (note how the printer is able to tell there is no filament during loading, so the sensor works)
  4. Once all loaded, connect octoprint
  5. Start a print
  6. Pull the filament out and hear the filament sensor trip/click
  7. Observe the printer extruding air and happily carrying on printing despite the filament having run out

  Note that on step 3, you can also "pretend load" by inserting the filament just past the sensor but not all the way into the extruder. This makes it easier and quicker to trip the sensor while printing as you can just yank the filament out of the sensor and is logically the same to the printer and the bug. It also saves on wasted filament because you're not physically extruding any during tests.

  Also note that printing from USB and yanking the filament out does trigger the filament change sequence => filament sensor not defective.

Please don't label as "wontfix" because it's only occurring over serial. This printer was (and still is) marketed as a printfarm workhorse, not supporting the filament sensor (that Prusa charges extra for) while printing from serial makes this printer *not* suitable for the exact scenario it's being marketed for.

  I have been able to reproduce both on 4.3.3 and 4.3.4.

**Expected behavior**
  The filament runout sensor triggers a filament change operation on the printer.

**G-code**
  Any model does it.

**Crash dump file**
  N/A

**Video**
  N/A

**Comment by JohnnyDeer** [comment] 2022-02-23 06:54
Hi @coaxial, this issue is duplicate of #1542. Please read this comment and below https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1542#issuecomment-975276123.
I´m closing this issue as duplicate.

**Closed by JohnnyDeer** 2022-02-23 06:54 UTC
Labels: bug
