### ISSUE TITLE
[BUG] Wrong image shown on MK4 screen when printing via PrusaLink

### ISSUE THREAD

**Issue by acwright** [prusa3d/Prusa-Firmware-Buddy#3057] opened 2023-04-15 17:41 UTC
**Printer type** - MK4
**Printer firmware version** - 4.5.4

**MMU upgrade** - None
**MMU upgrade firmware version** - None

**Describe the bug**
Wrong image shown  on MK4 screen when printing from PrusaSlicer via PrusaLink. 
  
**To Reproduce**
1. Select MK4 physical printer setup with PrusaLink
2. Slice model using PrusaSlicer 
3. Send print to printer by choosing "Upload and Print" dialog option
  
**Expected behavior**
Printer starts printing with correct model image shown on MK4 screen
  
I have attached an image that shows the problem. As you can see I am printing an articulated octopus model and the screen shows the last completed print (Prusa keychain; printed via USB drive) instead of the current print.

![IMG_3003](https://user-images.githubusercontent.com/608373/232244825-e7827b93-22cc-4798-8d14-abd830bd0293.png)

**Comment by Prusa-Support** [comment] 2023-06-13 17:53
It seems safe to call this issue a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3046.
The issue is present on the base code which is mutual for MK4 and XL printer models.
The other issue will be labeled reflecting both printer models, this issue will be closed instead.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-06-13 17:53 UTC
Labels: bug, duplicate, UI, network/data, MK4
