### ISSUE TITLE
Temp during mesh bed leveling on first layer calibration isn't "cold" temp

### ISSUE THREAD

**Issue by nwalke** [prusa3d/Prusa-Firmware-Buddy#368] opened 2020-04-14 22:45 UTC
During mesh bed leveling the mini cools to 170c, unless you're using the first layer calibration.  I just had it leave little blobs all over my print bed due to it running mesh bed leveling at 215c instead of 170c.

**Comment by JohnnyDeer** [comment] 2020-05-05 08:55
Hi @nwalke  , thank you for reporting, but this issue is already reported. I'm closing this one as duplicate of #157

**Closed by JohnnyDeer** 2020-05-05 08:55 UTC
Labels: duplicate
