### ISSUE TITLE
[BUG] Swapping filaments can trigger thermal runaways

### ISSUE THREAD

**Issue by kozross** [prusa3d/Prusa-Firmware-Buddy#3083] opened 2023-05-26 01:07 UTC
**Printer type** - MINI

**Printer firmware version** - 4.4.1

**Original or Custom firmware** - Original

**Optional upgrades** - 

**USB drive or USB/Octoprint**

USB drive.

**Describe the bug**

This issue can occur when changing from a higher-temperature filament to a lower-temperature filament (for example, going from ABS being loaded to PLA being loaded). In order to avoid clogging, the process to follow is like so:

1. Unload ABS.
2. Load PLA filament using the ABS setting so that the ABS is purged from the melt zone.
3. Unload PLA.
4. Load PLA filament using the PLA setting.

Failing to do this can cause partial clogs (and has for me in the past), so to be safe, I always do this when going from higher-to-lower-temperature filaments. At the same time, when going from step 2 to 3, or step 3 to 4, I can occasionally trigger a thermal runaway, due to the enforced cooldown to 170 after a load. This can sometimes happen mid-load, causing a forced reboot of the printer, and in bad cases requiring an extruder disassembly to clear out.

**How to reproduce**

1. Have a higher-temperature filament loaded, like ABS.
2. Follow the procedure described above to try and load PLA.
3. Note the occasional annoying thermal runaway false positives.

**Expected behavior**

I can see good solutions as any of the following:

* Allow loading of a filament at a higher temperature than its minimum.
* Don't force a drop to 170 on the nozzle post-load.
* Allow a special 'to colder' change setting that automates the process above.
* A more carefully-tuned thermal model to avoid this happening.

I consider these to be in rough order of complexity and adjacent inconvenience.

**G-code**

None relevant.

**Crash dump file**

None present.

**Video**

None exists.

**Comment by Prusa-Support** [comment] 2023-07-07 19:29
Thank you for your suggestion.

When a filament is unloaded, it is slightly purged and then withdrawn at the material temperature. This is usually enough but a little residue from the previous material may actually remain.

We already have an open issue about this.
I hope you don't mind me closing this issue as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1821.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-07-07 19:29 UTC
Labels: bug
