### ISSUE TITLE
Prusa Mini Stop button in display while filament is loading without function

### ISSUE THREAD

**Issue by Jan200696** [prusa3d/Prusa-Firmware-Buddy#370] opened 2020-04-16 14:53 UTC
Since there is sometimes a mechanical error while loading filament, I want to stop the process without having to restart the printer. A stop button is shown on the display, but this cannot be selected.

**Comment by JohnnyDeer** [comment] 2020-05-06 10:47
Hi @Jan200696 , it is purpose to not allow cancel during action, user can do it just before. Let's make this issue a feature request, about allowing user use cancel during action...

**Comment by JohnnyDeer** [comment] 2021-06-07 10:47
I´m closing this issue as duplicate of #222.

**Closed by JohnnyDeer** 2021-06-07 10:47 UTC
Labels: feature request
