### ISSUE TITLE
[BUG] XYZ Shifts randomly

### ISSUE THREAD

**Issue by rocrail** [prusa3d/Prusa-Firmware-Buddy#3173] opened 2023-07-31 07:30 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MK4]

**Printer firmware version** - [4.7.1]

**Original or Custom firmware** - [Original]

**USB drive**

**Describe the bug**
Middle in the print job there are randomly xyz shifts which destroys the object. 

**How to reproduce**
  It occurs randomly with the same GCODE.

**Expected behavior**
  Keep the XYZ positions to match the GCODE

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
  Please attach the crash dump file. This will make it easier for us to investigate the bug.

**Video**
  Please attach a video. It usually helps to solve the problem.

Forum links with pictures:
https://forum.prusa3d.com/forum/english-forum-original-prusa-i3-mk4-hardware-firmware-and-software-help/layer-shifts-galore/#post-666492

**Comment by shledge** [comment] 2023-07-31 14:20
I would check two things:
- grub screws
- slice new gcode on a different USB stick

**Comment by rocrail** [comment] 2023-07-31 16:26
The MK4 is factory assembled and grub screw are tightened.
The Original USB Stick, which comes with the MK4 is very slow.
The gcode is OK because otherwise it would make at every print the same shift. (PrusaSlicer)
I downgraded to firmware 4.7.0 but the 4th print in a row will have this shift. (randomly in which direction xyz)
I will reset from now on the MK4 between all print jobs.
I'm using Prusa Link for control.

**Comment by rocrail** [comment] 2023-08-01 05:08
For me it looks like an out of bound array index which overwrites variables related to the XYZ position.
The shift is completely random in all directions.

**Comment by murk-sy** [comment] 2023-08-01 07:40
Honestly this looks like bog standards layer shift due to either bad bed adhesion or extreme overhangs (as it seems to be in the photo of a cube in that thread).

1) Ensure you are using the correct sheet for the material
2) Ensure the bed is clean (you can easily see things like greasy areas by looking at light reflections)
3) Verify temperature settings are correct for the material
4) Consider using a brim and Z hop

This is unlikely to be a firmware issue.

**Comment by murk-sy** [comment] 2023-08-01 08:04
I'm glad you verified what I listed above isn't the case. Usually it's best to note the standard troubleshooting you've done since I've seen a lot of standard printing issues reported as firmware problems. Hopefully I didn't come across too crass about it.

To be clear, I *have* had random layer shift or bizzare movement issues on the Mini (#1793), but those were generally from old gcode that ended up corrupt due to the USB drive. Since the MK4 USB drive is connected to the screen rather than the mainboard, it is possible that that particular cable has intermittent connection issues.

If I understand correctly, after a reset, the first print *never* has issues? Or do you do a full power off+wait?
If you upload the next job during the print, can you verify the gcode has no issues?

**Comment by murk-sy** [comment] 2023-08-02 06:29
@dracoalien007 If resetting doesn't change the behaviour, it might not be the same issue. Based on the model gcode you provided, the fillet overhang could also be causing problems even if the print mostly (or fully) stays adhered to the bed. Your photo is actually the one I was looking at when i wrote my first comment for rocrail, I guess I thought he had a different username there since he linked it.

Additionally, rocrail is using stable firmware, not IS. Please check if the issue also happens on 4.7.1 so we can narrow things down. Printing 3-4 clips for each test should probably be fine, and I recommend you check on the print when it reaches the height where you originally had a layer shift - just to make sure the issue isn't caused by curling.

**Comment by rocrail** [comment] 2023-08-02 06:57
Maybe the number of files, which increases every day, on the slow USB-Stick will make the stick more slow.
I think you must check what happens if reading the data from the stick take more time then the firmware can allow.

**Comment by murk-sy** [comment] 2023-08-02 07:33
From my experience with the Mini (300+ files on the stock USB drive), amount and size of files doesn't really affect performance beyond slower file browsing. What I remember causing some issues in the past was regularly deleting files, causing file fragmentation - but it's been a while and I honestly could be remembering completely wrong. It's likely only related to directory listing as well.

**Comment by dracoalien007** [comment] 2023-08-02 12:02
> @dracoalien007 If resetting doesn't change the behaviour, it might not be the same issue. Based on the model gcode you provided, the fillet overhang could also be causing problems even if the print mostly (or fully) stays adhered to the bed. Your photo is actually the one I was looking at when i wrote my first comment for rocrail, I guess I thought he had a different username there since he linked it.
> 
> Additionally, rocrail is using stable firmware, not IS. Please check if the issue also happens on 4.7.1 so we can narrow things down. Printing 3-4 clips for each test should probably be fine, and I recommend you check on the print when it reaches the height where you originally had a layer shift - just to make sure the issue isn't caused by curling.

I appreciate the input.  I have tried the print on every imaginable firmware.  I probably just uploaded the one most recently on my computer.  Fail on all.  And none of them fail with only 4 clips. 

Call me noob, but what are you talking about with fillet overhangs?  These models are flat.  There should be no overhangs at all save the overhangs produced as a byproduct of closing the screw holes through the side of the clip.  Also, the shifting occurs way before it ever hits the hole.

Does the Code indicate there are overhangs somewhere?

**Comment by murk-sy** [comment] 2023-08-02 12:26
> I appreciate the input. I have tried the print on every imaginable firmware. I probably just uploaded the one most recently on my computer. Fail on all. And none of them fail with only 4 clips.
> 
> Call me noob, but what are you talking about with fillet overhangs? These models are flat. There should be no overhangs at all save the overhangs produced as a byproduct of closing the screw holes through the side of the clip. Also, the shifting occurs way before it ever hits the hole.
> 
> Does the Code indicate there are overhangs somewhere?

From your gcode file - red is the current fillet overhang, blue is a more optimal 45° chamfer that should generally be used to guarantee printability. 
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/1211672/32f15ef0-32ae-4a72-8545-03f2924b5ac1)
If the issue is what I suspect it to be (specifically curling), cutting off the bottom 0.60mm (or honestly even half that) of the model will resolve it. I believe it is failing at a larger clip amount because the clips cool down sufficiently to cause the axes to skip steps on crash. Other possible solutions are setting a higher fan speed or a fairly high z hop.

**Comment by rocrail** [comment] 2023-08-02 12:28
Did you also so test with different USB stick?

**Comment by rocrail** [comment] 2023-08-02 12:38
If such tiny overhang will trigger a shift ????
An overhang could lead to a poor print result but certainly not to such a shift.

**Comment by dracoalien007** [comment] 2023-08-02 17:16
Ah-I see the filets now.  My bad. 

I'm printing the same file (ish) on PLA now, same drive.   I do find it odd that I have SO MANY shifts occurring after the filet if that's a possible cause.  It's a 1.5 hour print, so I'll know soon.  After it finishes/fails, I'll print it again.  Also, I have a camera on it.  We will be able to see if it is "crashing".

But I gotta say.... Wow.  If that "overhang" (note that it's zoomed WAAAAY in) causes a crash, that's a serious issue.  It's barely more than elephant foot compensation.

**Comment by jvasileff** [comment] 2023-08-02 18:17
I think @murk-sy might be right. I was very easily able to create Y and X layer shifts by pushing on the heat bed and the extruder while printing. The steppers just lost their position and kept going. I guess the MK4 doesn't have crash detection?

This is very different from my experience with the MK3, which requires a ton of pressure to overcome the torque of the steppers, and even then, prints generally continue fine after crash detection and re-homing.

This was with input shaping.

FWIW - I've had no layer shifts with regular prints so far, including when I tried @dracoalien007's gcode.

![IMG_0780](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/236050/f23b27bc-924b-4c3b-9645-b311761c6b11)

**Comment by dracoalien007** [comment] 2023-08-02 18:36
> I think @murk-sy might be right. I was very easily able to create Y and X layer shifts by pushing on the heat bed and the extruder while printing. The steppers just lost their position and kept going. I guess the MK4 doesn't have crash detection?
> 
> This is very different from my experience with the MK3, which requires a ton of pressure to overcome the torque of the steppers, and even then, prints generally continue fine after crash detection and re-homing.
> 
> This was with input shaping.
> 
> FWIW - I've had no layer shifts with regular prints so far, including when I tried @dracoalien007's gcode.
> 
> ![IMG_0780](https://user-images.githubusercontent.com/236050/257903603-f23b27bc-924b-4c3b-9645-b311761c6b11.jpeg)

Wow.  That's pretty crazy.  It's hard to believe a single clip (likely less than a few grams) is causing such a catastrophic crash that it would shift the entire print head 3cm.  On the MK3, it would just stick that sucker to the side of the next object and keep on trucking.

The only thing that doesn't track is why on some large objects (which definitely aren't curling) I get a failure at the very top of the file.  One was a 14 hour print.  Based on the shift, it looks like it failed right around 13.5 hours.  It's the chimney that shifted of the attached file.
[Desktop.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12243589/Desktop.zip)

**Comment by jvasileff** [comment] 2023-08-02 18:49
Yeah, I'm pretty surprised your water clips gcode would curl & crash. But when there is a collision, there may be a lot more force that it would seem. I've definitely had crashes on my MK3s, just with better recovery.

**Comment by jvasileff** [comment] 2023-08-02 19:13
> surprised your water clips gcode would curl & crash

Unless... maybe there is a problem with Z? If for whatever reason Z fails to lift when it should, it may drop too low and crash into the part during X or Y movements.

**Comment by rocrail** [comment] 2023-08-03 14:27
Fast USB does not do the trick; After reset a print with gcode which printed OK before...
![MK4-shift](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/67797224/986afbcc-36b7-46dc-868d-dd9fe85b08b6)

**Comment by rocrail** [comment] 2023-08-03 16:36
The PrusaLink(Beta) is always open in the Google Chrome browser. (Does not work with Safari...) 
Maybe this is a hint.

**Comment by rocrail** [comment] 2023-08-04 05:43
The Technical Support did ask per Email the Serial numbers of the 4 stepper motors.
Maybe we have a bad motor badge.

BTW: Reverted to firmware 4.7.0

**Comment by rocrail** [comment] 2023-08-04 16:22
The 4th print job got a shift.
It looks like the hot-end collects a lot of filament and after a while it drops the filament. This drop will get hard and at the next layer the stepper motor will hang and causes a shift.
![hotenddrip](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/67797224/812da22e-a158-4dc2-ad96-8fb05f214514)
The Hot-End get dirty very soon and if enough filament is collected the shift will certainly come...

**Comment by rocrail** [comment] 2023-08-04 17:28
IMHO the stepper motors are fed with a too low voltage to make them silent, but every small obstacle will cause a shift.
The Hot-End fan is very loud so to increase the voltage for the steppers will no one notice.

**Comment by rocrail** [comment] 2023-08-05 06:14
I added a "Prusa Nextruder Silicone sock" to the Hot-End; Maybe it prevent clumbs.

**Comment by zachsa999** [comment] 2023-08-24 12:55
Note: it only does it on the horizontal axis

**Comment by zachsa999** [comment] 2023-08-24 14:36
Sorry for the spamming.


I checked the tension on the belts, it appears that the bed axis might be slipping. I tightened it up, but I don't think that fixed it as the problem appears on the gantry axis as well.

**Comment by Prusa-Support** [comment] 2024-01-31 22:16
This issue has been silent since last Summer. Major firmware changes occurred shortly after, with the final release of FW 5.0.0 (enabling Input Shaper). Plus, there have been minor further tunings in the axis testing and the motion systems later.

We couldn't reproduce this problem except for hardware/assembly-related reasons.
Some of these problems may find a root in the first layer preparation, the belt tensioning, and the presence of obstacles/friction along the axis.
Some other side concerns about the USB flash drive interferences and specifically tricky print scenarios mentioned in this thread may also be valid but rather unlikely. These cases may potentially be ruled out by replacing the flash drive and analyzing the specific print with the help of our Customer Support (or comparing the results with other simpler print objects and approved profiles/filaments.

I wonder if the problem persists with the most recent firmware, as the issue may actually be obsolete by now.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment] 2024-02-21 17:02
It seems safe to close this issue as stale.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2024-02-21 17:02 UTC
Labels: bug, unable to reproduce, HW issue, troubleshooting
