### ISSUE TITLE
[BUG] File cannot overwritten when sent via Prusalink

### ISSUE THREAD

**Issue by dibor** [prusa3d/Prusa-Firmware-Buddy#2863] opened 2022-12-30 14:40 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MINI+

**Printer firmware version** - 4.4.1-RC1+4188

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint**
  Prusalink

**Describe the bug**
  File cannot be overwritten

**How to reproduce**
  Try to send file with same file name

**Comment by Prusa-Support** [comment] 2023-01-31 12:24
Thanks for reaching us.
This is a duplicate of issue https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2447.

Please follow the already existing issue.
This one will be closed as a duplicate.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-01-31 12:24 UTC
Labels: bug
