### ISSUE TITLE
[FEATURE REQUEST] Display time left before filament change

### ISSUE THREAD

**Issue by icepick3000** [prusa3d/Prusa-Firmware-Buddy#3138] opened 2023-07-14 12:18 UTC
The old MK3 i had used to show how much time was left before i needed to change filament (in case i set up prusaslicer with multiple color layers). The MK4 is missing this feature.

**Comment by Prusa-Support** [comment] 2023-10-04 17:55
Thanks for reporting, however, this issue should be closed as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3107.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-10-04 17:55 UTC
Labels: feature request
