### ISSUE TITLE
[ENHANCEMENT] When pausing a print, please park the Z axis higher

### ISSUE THREAD

**Issue by ShadowDrakken** [prusa3d/Prusa-Firmware-Buddy#3007] opened 2023-02-24 16:42 UTC
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MINI/MINI+
**Optional upgrades** - N/A

**Is your suggested improvement related to an existing problem? Please describe.**
Please park the Z axis higher up when pausing a print so that the hot end is accessible. It would help immensely for troubleshooting things like build-up and small clogs if we could get hands and small tools under the hot end.

**Describe the expected functionality**
Ideally, the Z axis should park at 160 when prints are paused to give access to the hot end and the print.

**Comment by Eldenroot** [comment] 2023-02-25 14:32
+1

**Comment by edwardhorsford** [comment] 2023-03-04 17:35
+1 for this - I pause to insert magnets, and a higher z would mean I can get to the print more easily.

**Comment by Prusa-Support** [comment] 2023-04-06 12:48
Thanks for your feedback.
Now please allow me to close this issue as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2366. 

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-04-06 12:48 UTC
Labels: enhancement
