### ISSUE TITLE
[BUG]STOP button not actionable

### ISSUE THREAD

**Issue by mix579** [prusa3d/Prusa-Firmware-Buddy#1483] opened 2021-06-23 01:14 UTC
**Printer type** - [MINI]

**Printer firmware version**-  4.3.1

**Original or Custom firmware** Original

**Describe the bug**
 Confusingly, several screens feature a STOP button but it is not possible to actually select it. To interrupt the ongoing process, it is necessary to press the reset button. For one example, see https://i.imgur.com/A4ax2Nm.jpg

**Expected behavior**
The button should be actionable and end the ongoing activity, or not be displayed at all.

**Comment by JohnnyDeer** [comment] 2021-06-24 10:28
Hi @mix579, thank you for reporting. We are aware of this issue and it is duplicate of #222 . I´m closing this one.

**Closed by JohnnyDeer** 2021-06-24 10:28 UTC
Labels: bug
