### ISSUE TITLE
[FEATURE REQUEST] Replace the Octoprint Logo

### ISSUE THREAD

**Issue by BigAl66** [prusa3d/Prusa-Firmware-Buddy#3973] opened 2024-05-03 13:18 UTC
I use the MK4 and all the time I do serial printing the Octoprint Logo will show up on the display.

Two things bother me about this:

1. I'm not using Octoprint. A more universal logo would be nice. Or just a text "Serial Printing".

2. My old MK3 show a lot of additional information like print progress even when I print through the serial port. Now we have a big screen and just a useless logo is shown. Please give us back at least all the information we had on the MK3 display.

**Comment by Prusa-Support** [comment] 2024-06-25 17:49
Thanks for your suggestion.
However, this issue should be closed as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2377.
It also partially duplicates https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3653 and https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3846.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2024-06-25 17:49 UTC
Labels: feature request
