### ISSUE TITLE
[BUG] Printhead crashes into buildplate sporadically

### ISSUE THREAD

**Issue by BlueTiger12** [prusa3d/Prusa-Firmware-Buddy#3079] opened 2023-05-25 14:05 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches. -> Done

**Printer type** - [MINI]

**Printer firmware version** - [4.4.1+4194]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor, ESP-01S]

**USB drive or USB/Octoprint**
  USB flash drive

**Describe the bug**
  Printhead crashes into buildplate sporadically after a print is aborted during bed-mesh-leveling followed by moving the z-axis in the settings menu. This happens only, if the printhead stays at z-position 1 after aborting the bed-mesh-leveling and does not move to z-position 22, which it normaly should (sporadic issue)

**How to reproduce**

**Sporadic Issue -> May need several tries to reach the failed state**
  1. Start any print
  2. During Bed-Mesh-Leveling, abort the print

**If the hotend moves upwards to z-position 22:**
      -> Correct behaviour
      -> Restart print
      -> GoTo 2.

**If the hotend stays at z-position 1:**
  **!! You have reached the failed state!!**
  4. Go to settings -> move axis (z-axis will show position 1)
  5. Activate z-axis
  6. As soon, as you turn the dial in any direction, the printhead will crash into the build-plate and press it down
  7. Printer will operate normally after that (you will have to move up the z-axis before, or you will damage even more)

**Please note, that this is the only occasion, any axis of the printer behaves faulty. If I reset the printer after it has entered the failed state, I can print normally without any issues**

**Expected behavior**
- Z-axis moves up if the dial is turned clockwise
- Z-axis moves down for only 1 step if turned counterclockwise

**Unsuccessful steps to resolve the issue**
- Factory reset
- Print different file
- Disable networking (first occurence was with a print via prusa-link)
- After reaching the failure-state, swap motor cables of z and x axis -> Identical behaviour on x-axis when moving z-axis in settings

**G-code**
  Reproduced on multiple files. Here is an example file
[16mm Rail Hook v7_0.2mm_PLA_MINI_15m.gcode.txt](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/11565441/16mm.Rail.Hook.v7_0.2mm_PLA_MINI_15m.gcode.txt)

**Crash dump file**
  No software crash

**Video**
Video how the printer crashes into the build-plate:
  https://drive.google.com/file/d/1-y1wzBRPIqd6-81VRRR2tx53MgebyVtv/view?usp=sharing
Reproduced Bug from start to finish (i move the z-axis upwards inbetween to not damage my printer even further)
  https://drive.google.com/file/d/108oWu5EFHlmWyJRimwCOpu-YkTEN1WoR/view?usp=sharing

**Hypothesis**
2 Variables exist for the z-position. One representing the z-position of the hotend in the user-interface and a second one for the real estimated position of the hotend
When aborting the bed-mesh-leveling, these seem to get out of sync sporadially.
The ui-variable contains the actual hotend position of 1, while the estimated-position-variable contains the value 22, which is the position the hotend should be after the bed-mesh-leveling was aborted.
If the user now adjusts the ui-variable of the z-axis it goes either to 0 (counterclockwise adjustment) or to 2 (clockwise adjustment).
The controll algorythm detecs a discrepancy between requested z-position (0 or 2) and estimated z-position (22) and corrects this by a movement of 22 or 20 steps into negative z-direction.
As the printhead is actually at position 1, it will crash into the build-plate.
This would explain:
- why the z-axis moves into negative direction independently of the direction, the knob is turned
- why the printer acts normally after this single faulty movement
- why it does not happen, if the printhead moves to z-position 22 after aborting the bed-mesh-leveling, but only if it stays at z-position 1

**Comment by Prusa-Support** [comment] 2023-06-14 11:40
Hello, thank you for reporting the issue, and for the details and videos. I'll report this to our devs to check in more detail, we will try to reproduce and understand more and hopefully have a fix asap. 

In case of more info I'll update on this thread, and certainly let me know in case of anything, I remain available at any time. 

Alessandro Pantaleo
Prusa Research

**Comment by BlueTiger12** [comment] 2023-06-14 11:51
Hello Alessandro Pantaleo,
thank you for your reply.

In case of any questions, or if you need additional tests / need me to test a new firmware, please also do not hesitate to contact me.

Best Regards,
Daniel

**Comment by Prusa-Support** [comment] 2023-09-08 15:19
Yes, the printer should move up to position Z=22 but for some reason remains at Z=2.
However the printer "believes" to be at position Z=22 and will move down by about 20 mm as soon as you move the Z up or down starting from the current virtual Z=2 position.

I get that the error appears sporadically but we are not able to reproduce it.
I wonder if the hardware plays a role or if this is entirely on the firmware side.

- Please temporarily enable both "Z-axis coordinate" and "Z-height" as footers and see if either will update their position to Z=22 while the Z-axis physically remains stuck.
- It seems that your video has no audio but please focus on the noises as I don't want to Z axis to actually be trying to move but struggling.
- Try to reseat the trapezoidal nut, avoiding tightening its screws with force.
- We can't exclude that the Z axis is skipping steps due to a hardware fault so possibly test it by hand and via printer's commands while disassembled.

Michele Moramarco
Prusa Research

**Comment by BlueTiger12** [comment] 2023-09-08 22:43
Hi Michele Moramarco,
thank you for your reply.

I removed the Audio in the Background because my Child was noisy next to me.
But I am 100% certain, that the z-axis is not skipping steps.

I don't think, that the Z-axis has any hardware fault, as i have perfect print results with the Mini every time.
I recently did a vase-mode test over the full z-axis range, which turned out perfectly.

I will try to reproduce it with the requested footer and with audio the next days.

Daniel

**Comment by BlueTiger12** [comment] 2023-09-09 18:49
Hi Michele Moramarco,
thank you for your reply.

I removed the Audio in the Background because my Child was noisy next to me.
But I am 100% certain, that the z-axis is not skipping steps.

I don't think, that the Z-axis has any hardware fault, as i have perfect print results with the Mini every time.
I recently did a vase-mode test over the full z-axis range, which turned out perfectly.

I will try to reproduce it with the requested footer and with audio the next days.

Daniel

**Comment by BlueTiger12** [comment] 2023-09-09 18:50
Hi Michele Moramarco,

somehow my message was not sent.
Here is a picture of the requested footer when the issue happens (happened directly on first try) and also of the height of the printhead.

![20230909_204758](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/12852382/bac7b844-17e9-4139-9cfd-f3598973285b)
![Uploading 20230909_204802.jpg…]()

**Comment by Prusa-Support** [comment] 2023-10-17 19:02
Thanks. Is the footer reporting _21:85_ the "Z-axis coordinate"?
It seems it was updated with the correct final value but the Z-axis didn't move.

So far we haven't been able to reproduce the problem and apparently, we didn't receive any similar report.

A video with clear audio may help us understand if the Z-axis attempted the movement at all.
Also, so far we can't exclude a too-tight or deformed trapezoidal nut, a problematic Z motor or a specifically heavy x-axis/extruder-block due to the design modifications.

On a side note, the new firmware version will be substantially different and, among the other changes, it seems it will allow the user to abort the MBL right away without fulfilling the operation.
Probably a neater management of the commands queue will improve the "stop print" behavior too - and hopefully resolve this issue if it is actually firmware-related.
Feel free to test the new FW 5.1.0-alpha1 but please mind it is an alpha version, hence it may be quite unstable! If you test it, you do it at your own risk.

Michele Moramarco
Prusa Research

**Comment by BlueTiger12** [comment] 2023-11-10 14:49
Hello Michele,

sorry, that my answer took that long.
In the footer menu, the position with the number 21:85 is called z-height.

This is really strange, as i have it really easy to reproduce it.
I can say for sure, that this is no mechanical problem, as there is no blocked stepper or anything (i know how this sounds, when it travels to far up.
Also, i have absolutely zero print issues. This happens only with this specific circumstance.

I managed to make a video where you can see 2 runs. The first one shows how the print is aborted correctly and in the second run it shows the faulty behaviour. In the end i also go into the footer menu, so you can see what each item is. I also made sure, that everything else is quiet, so you can hear as much as possible.

I am not surprised, that this is no common problem, as it needs several steps to crash into the build plate.
You need to abort the print during bed-leveling, then the error has to occur and then you have to manually move the stepper in the settings menu. If you just resume printing, it will just move the buildplate back and then start bed-leveling, so it does not move in z-axis before using the SuperPINDA.

I have high hopes, that a new firmware can resolve this issue.
Unfortunately, I couldn't find the time yet to test the new firmware.
I will report back, when i maganged to test it then, but i am positive, that this might resolve the issue.

**Comment by Prusa-Support** [comment] 2024-01-02 14:22
Keeping the firmware up to date is recommended but you can still downgrade it.
https://help.prusa3d.com/article/firmware-updating-mini-mini_124784

Michele Moramarco
Prusa Research

**Comment by dpark12300** [comment] 2024-01-04 16:52
Try adjusting the PINDA or MINDA

**Comment by BlueTiger12** [comment] 2024-01-04 18:15
> Try adjusting the PINDA or MINDA

@dpark12300 could you please explain a little more, why you think, that this will solve the issue? Because I see absolutely no indication, that this is related to the issue.

**Comment by dpark12300** [comment] 2024-01-04 18:20
Just guessing. My printhead was denting the bed of my MINI+, and that fixed it.

**Comment by BlueTiger12** [comment] 2024-01-04 18:30
@dpark12300 Did this also only happen only sporadically, when you aborted the print during probing as described above?
In case, you didn't read the problem description completely, my Mini is printing without any problem, it just shows a sporadic issue in a very specific circumstance.

**Comment by Prusa-Support** [comment] 2024-01-27 16:33
Thanks for your feedback, Daniel.
I'll gladly give a look at the other issue and close this one right away at this point.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2024-01-27 16:33 UTC
Labels: bug, unable to reproduce, HW issue, troubleshooting, 4.4.1, MINI
