### ISSUE TITLE
Printer crashes when preheating in low temperature

### ISSUE THREAD

**Issue by deepthought-64** [prusa3d/Prusa-Firmware-Buddy#365] opened 2020-04-13 21:13 UTC
When trying to preheat the printer at a temp of 13°C (assume it does it below 15°C) the printer firmware crashes and gets reset by the watchdog. 

Expected behaviour would be that it should either:
- show a warning that it is too cold to pring (which i personnally dislike, because why should i not be able to print at 13°C?)
- show a confirmation dialog telling me that it is cold but lets me continue, or
- just let me print (I'd perfer that)

See video here: https://photos.app.goo.gl/DXRSgSNTFWSDb93r5

I'm using firmware version 4.0.4

**Comment by x10102** [comment] 2020-06-24 09:43
Yes please. I want this.

**Comment by Hl2run** [comment] 2020-06-24 11:38
Same here please.

**Comment by Vic-Y** [comment] 2020-07-23 03:33
I think I have a related problem with firmware 4.1.0. My printer is in a cool room in my house, under an air vent. With the air conditioning on, the printer temperature is below 15C when idle. When I select "unload filament", printer displays an error message and forces a reset.

![IMG_1533](https://user-images.githubusercontent.com/62916399/88249830-d758be00-cc62-11ea-8882-7eed7edce376.JPG)

![IMG_1534](https://user-images.githubusercontent.com/62916399/88249835-da53ae80-cc62-11ea-8646-df5879787ed6.JPG)

**Comment by JustAnother1** [comment] 2020-07-27 23:24
The problem is probably connected to a safety issue. If the temperature sensor is disconnected or short circuited the temperature read will probably be around what you measure.  To avoid burning down your house the firmware tries to detect these error conditions (That is what the MINTEMP is about)

If you really need to print at those low temperatures then you can change the MinTemp setting in the firmware.

**Comment by JohnnyDeer** [comment] 2020-12-14 09:46
Hi, in version 4.3.0-RC1 mintemp is reduced to 10 ° C, which will solve this issue. @deepthought-64 can you confirm it please?

**Comment by deepthought-64** [comment] 2020-12-14 09:49
HI @JohnnyDeer, thanks for the notification. Will update and test it!

**Comment by deepthought-64** [comment] 2020-12-14 10:52
I can confirm, that pre-heating works now below 15°C but however if the printer is below 10°C it still crashes when trying to preheat. 
I expect that instead of going into a watchdog-reset it should just shows a dialog telling the user that the temp is too low. Instead it resets and shows a mintemp error and instructs me to check the printhead thermistor for damage in the wiring.

![IMG_20201214_114925](https://user-images.githubusercontent.com/5528887/102072924-d1769b80-3e02-11eb-9d51-2ff0c73a0bad.jpg)

**Comment by JohnnyDeer** [comment] 2021-02-10 09:38
Mintemp lowered to 10°C is minimum we can do given the machine limits, values are unified with the MK3 series. I´m closing this issue, thank you for understanding.

**Closed by JohnnyDeer** 2021-02-10 09:38 UTC
