### ISSUE TITLE
[BUG] Wi-Fi still connects when an ethernet connection is present, regardless of active link configuration

### ISSUE THREAD

**Issue by Lyude** [prusa3d/Prusa-Firmware-Buddy#4206] opened 2024-09-14 19:57 UTC
### Printer model

MK4

### Firmware version

6.2.0-alpha1

### Upgrades and modifications

ASA parts instead of PETG

### Printing from...

PrusaLink via a hostname

### Describe the bug

When both a configured wifi connection and ethernet connection are available, the printer will always connect to both networks instead of just one. This ends up leading to a subtle issue: typically, one would expect the printer to receive jobs over ethernet if an ethernet cable is present. However - WiFi of course takes a bit longer to connect then the ethernet connection does. As a result, it seems like the hostname first gets assigned to the wired connection - and then the wireless connection afterwards. Thus - even with the active link set to ethernet, jobs I send to the printer's hostname over PrusaLink end up going over WiFI instead.

### How to reproduce

* Set up a WiFi connection on the printer and ensure it works
* Set a custom hostname on the printer, and use this hostname in PrusaSlicer to send jobs to it
* Set up an ethernet connection on the printer
* If the problem doesn't occur after this, restart the printer once without changing anything else. It should happen afterwards.

### Expected behavior

The printer should likely just deactivate its WiFi connection whenever a working ethernet connection is present, unless the user specified otherwise. I assume hostname assignment on people's LANs when two interfaces ask for the same name is not the most predictable thing generally, so ensuring only one interface is active at any given time should fix the problem.

### Files

https://github.com/user-attachments/assets/03f8ee26-94d7-4b76-9b6e-444b52071f04

**Comment by danopernis** [comment] 2024-09-17 10:14
Looks like this is not a bug, but a feature. But the feature is poorly documented. The active interface simply means the interface used for outgoing traffic. To disable the interface, you should either not connect it physically or not configure it (i.e. empty SSID in case of Wi-Fi). Also, initialization is inherently racy.

I fully agree that this is poorly documented and counterintuitive, but this is how the product department wants it to be. Therefore, I am closing this issue as it is not a bug. Feel free to open feature request if you want to change this behaviour. Maybe if there is enough support for this, things will actually change. Thank you for understanding.

**Closed by danopernis** 2024-09-17 10:14 UTC
Labels: bug
