### ISSUE TITLE
[BUG] Wrong remaining time

### ISSUE THREAD

**Issue by ThomasCZ** [prusa3d/Prusa-Firmware-Buddy#2794] opened 2022-12-03 13:08 UTC
**Printer type** - MINI

**Printer firmware version** - 4.4.0

**Original or Custom firmware** - Original

**Describe the bug**
Remaining time in PrusaLink is wrong. I do not think, this is bug in PrusaLink, the printer is probably providing wrong time.

![chrome_usheIc57Rd](https://user-images.githubusercontent.com/7516715/205442403-7c5d2ca7-e210-4b65-b5e3-c61d2f28b3f7.png)

**Comment by Prusa-Support** [comment] 2022-12-27 19:00
Thanks for reporting.

Does that happen with a specific print only?
Does the problem persist with [FW 4.4.1-RC1](https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v4.4.1-RC1)?

Michele Moramarco
Prusa Reseearch

**Comment by nighthawk8301** [comment] 2023-03-07 18:38
+1 

I got this bug in the 4.4.1 release version, while printing some of the Prusa mini printable parts.
After a few minutes the bug was healing itself and the correct remaining time was displayed again.

**Comment by Prusa-Support** [comment] 2023-03-28 12:11
As described at https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1321#issuecomment-1452345163, there are various reasons for the clock and the print time estimate not being extremely accurate, or temporarily offset.

The auto-heal is actually a sign that code `M73` regularly occurs during the print (expected behavior).

Because the described problem is too generic and seems actually related to the printer's firmware, this issue should be closed as a duplicate of issues https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1067 or https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1321.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-03-28 12:11 UTC
Labels: bug
