### ISSUE TITLE
[BUG]Wizard got stuck at preparing hotend

### ISSUE THREAD

**Issue by Fliens** [prusa3d/Prusa-Firmware-Buddy#1154] opened 2020-12-14 11:30 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]

**Printer firmware version**-  [e.g. 4.0.5, ...]
4.3.0-RC1

**Original or Custom firmware** [Original/Custom]
Original
**Optional upgrades** - [e.g. Filament Runout Sensor]

**USB drive or USB/Octoprint**
USB
**Describe the bug**
I just ran the wizard from the calibrate menu and when it tested the heating elements: hotend and heatbed it got stuck at preparing the hotend. The heatbed completet all it's tests but the hotend didn't even heat up!

**Expected behavior**
Hotend should usually heat up and complete the test

**Comment by JohnnyDeer** [comment] 2021-01-11 12:26
Hi @Fliens, could you please upload video of this issue? Thank you.

**Comment by Fliens** [comment] 2021-01-13 20:50
Unfortunately not, only had this issue once

**Comment by JohnnyDeer** [comment] 2021-01-18 09:53
We are unable to reproduce it or find out the problem. If you will have this bug again please open new issue with most information as will be possible. I´m closing this one as "can't reproduce". Thank you for understanding.

**Closed by JohnnyDeer** 2021-01-18 09:53 UTC
Labels: 4.3.0-RC1, bug
