### ISSUE TITLE
Can’t set new nozzle temperature while printing 

### ISSUE THREAD

**Issue by dizlee** [prusa3d/Prusa-Firmware-Buddy#4173] opened 2024-08-31 03:48 UTC
### Printer model

XL Multitool

### Firmware version

6.0.4

### Upgrades and modifications

None

### Printing from...

PrusaLink

### Describe the bug

During printing, When I try to change the nozzle temperature to a new value, as soon as the head is parked (for other head to print) and then picked again, the temperature jumps back to the old value, not the new one I set.

### How to reproduce

During printing with multitool, set the current nozzle temp to new value (different from what you used in slicer/gcode).
Tune>Nozzle # Temperature
Click to change temperature value and click again to confirm.
The nozzle will be set to the new value for now.
Wait until it parks and be picked again, check the nozzle temperature, it will be back to the old gcode value.

### Expected behavior

The nozzle temperature should be set to the new tuned value for the rest of the print, or until the value is changed again manually by the user.

### Files

https://youtu.be/y1q01iiYvGw?si=uqOgFYQB9OKYha8B

**Comment by murk-sy** [comment] 2024-08-31 10:49
Duplicate of:
- https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3343

**Closed** 2024-09-06 13:00 UTC
Labels: bug, duplicate
