### ISSUE TITLE
[QUESTION] <Files uploaded to directories land in root directory anyway>

### ISSUE THREAD

**Issue by hainjedaf** [prusa3d/Prusa-Firmware-Buddy#3003] opened 2023-02-23 17:50 UTC
Min+ succesfully upgraded to wifi and connected to PrusaSlicer.

Upon uploading, I choose a subdirectory and filename using / (slashes) as indicated by PrusaSlicer.
Files get placed in USB root.

I've tried:

./dir/file.gcode
/dir/file.gcode
dir/file.gcode

Also I checked if spaces, underscores and minus symbols mattered; they don't.

**Comment by cb88** [comment] 2023-04-04 19:42
I would like this feature to be added also. 

Uploading to directories. And printing from directories. I already used this in the past from the LCD interface so my files were organized and I didn't have to delete anything (since sometimes I need to reprint something again months later).

**Comment by Prusa-Support** [comment] 2023-04-05 13:26
Thanks for the suggestion.
 
 Now please allow me to close this issue as a duplicate of issue https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2506.
 
Moreover, this behavior is expected to be improved in the near future as mentioned in the relevant issue of the _Prusa Link_ repository https://github.com/prusa3d/Prusa-Link-Web/issues/290.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-04-05 13:26 UTC
Labels: question
