### ISSUE TITLE
[ENHANCEMENT] Enable Scrolling Text for File Name During Printing

### ISSUE THREAD

**Issue by AlexDCode** [prusa3d/Prusa-Firmware-Buddy#766] opened 2020-08-07 23:13 UTC
Please add text scrolling for the file name during printing as on the file menu. Sometimes I would like to see the entirety of the text but is limited due to screen size, but scrolling text would hugely help.

**Comment by JohnnyDeer** [comment] 2020-08-10 05:03
Hi @AlexDCode, this is duplicate of #249 and this feature is on our to do list :) I´m closing this issue as duplicate.

**Closed by JohnnyDeer** 2020-08-10 05:03 UTC
Labels: enhancement
