### ISSUE TITLE
[BUG]<ORIGINAL PRUSA MINI - Blue screen - TASK: webServerTask> #2821

### ISSUE THREAD

**Issue by Psychorages** [prusa3d/Prusa-Firmware-Buddy#866] opened 2020-09-04 20:48 UTC
Printer type - ORIGINAL PRUSA MINI
Printer firmware version- 4.2.0-final+2067

Describe the bug
not sure, but i may have try to access to Prusa connect at this moment of print
Blue screen @ 74% print job :
![91994292-be016200-ed36-11ea-8678-b63e05084002](https://user-images.githubusercontent.com/52109462/92283182-a1fcec80-eeff-11ea-8090-7daa1aeb69d7.jpg)

To Reproduce
print with lan on

Expected behavior
no blue screen :')

G-code
[Base_0.2mm_ABS_MINI_6h46m.gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/5176854/Base_0.2mm_ABS_MINI_6h46m.gcode.zip)

**Comment by zoltan-l** [comment] 2020-09-05 10:51
Hi ,it is solved by 4.2.1 including the root cause ,should you find it again, let us know please.

**Comment by JohnnyDeer** [comment] 2020-09-07 05:18
Hi @Psychorages as my colleague wrote this is fixed in 4.2.1 also it´s duplicate of #763 #771 #791. I´m closing this issue as duplicate.

**Closed by JohnnyDeer** 2020-09-07 05:18 UTC
Labels: bug
