### ISSUE TITLE
[BUG] Enclosure fan not spinning when starting print

### ISSUE THREAD

**Issue by ngolf** [prusa3d/Prusa-Firmware-Buddy#4229] opened 2024-09-30 17:09 UTC
### Printer model

XL 5T, with original prusa XL enclosure.

### Firmware version

6.1.3+7898

### Printing from...

Prusa Connect

### Describe the bug

When starting a print from prusa connect, I get the following message about the fan not spinning.

![Screenshot 2024-09-30 180631](https://github.com/user-attachments/assets/442a61ef-5880-4857-8dec-a647496b0f8a)

The "enclosure" setting on "tune" is then automatically turned off.

If I turn back on, I see a brief message about checking the fan, and the fan starts normally.

Connections are OK, there is nothing blocking the fan, and I can feel the air flow at fan exit, as well as see the fan RPM on telemetry.

### How to reproduce

Send a print to the printer (enclosure setting must be on)

**Comment by JCDwight** [comment] 2024-10-01 02:12
I have the same error.  I have to walk to the printer every time and turn it on if I want it on.  This just started happening recently.

**Comment by danopernis** [comment] 2024-10-01 12:25
@ngolf @JCDwight thanks for reporting, this seems like a duplicate of #4186

Please add your comments to #4186 and close this one in order to keep the issues more organized.

**Comment by ngolf** [comment] 2024-10-01 17:37
duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/4186

**Closed** 2024-10-01 17:36 UTC
Labels: bug, duplicate
