### ISSUE TITLE
[BUG] PRUSALINK over WIFI STATIC IP not Working

### ISSUE THREAD

**Issue by seifer69er** [prusa3d/Prusa-Firmware-Buddy#2838] opened 2022-12-17 22:11 UTC
Using Prusa Mini firmware 4.4.1beta over wifi with an ESP-01S 4mb

Connection via DHCP is  ok,
However connection via static is problemenatic.
Unable to set static ip address when selecting static over wifi.
addresses are greyed out and unable to force an IP

This may just be a settings issue, but should be exported as part of the credentials list for update

**Comment by TheMoen** [comment] 2022-12-21 23:15
I can not set a static IP over wired connection either. IP, mask and GW values are gray.
DHCP works fine

**Comment by Prusa-Support** [comment] 2023-01-18 16:19
Please allow me to close this issue as duplicate of issue https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2367.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-01-18 16:19 UTC
Labels: bug
