### ISSUE TITLE
Progress Bar Suggestion

### ISSUE THREAD

**Issue by IanPendlebury** [prusa3d/Prusa-Firmware-Buddy#3048] opened 2023-04-15 09:58 UTC
I was just stood watching my Mini+ and I was wondering how long I had wait before the next pause for a colour change. The idea hit me that it would be great if there was some sort of tick or mark on the interface progress bar to show me how far off the next print pause was.

**Comment by gold1640** [comment] 2023-04-19 09:37
Mk4 firmware also does not show the time to a colour change - would be nice to add this to the main graphic sreen, perhaps as well as current z hight, nozzle and heatbed temperatures.

**Comment by MrJones4u** [comment] 2023-05-01 14:47
Yes, time and layer count till next color change sounds like a great idea. 
Also I find the current Z height is apart from the remaining time the one most looked at values.

**Comment by Prusa-Support** [comment] 2023-06-01 21:29
Thanks for your suggestion.

However, this issue is pretty much a duplicate of the existing issue https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/1062.
Please allow me to close this issue as a duplicate and feel free to share your further ideas and suggestions on the already existing issue.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-06-01 21:29 UTC
Labels: feature request
