### ISSUE TITLE
[BUG] 6.2.0-alpha1 Firmware XL - Printer no longer connects to PrusaConnect / Wifi flapping

### ISSUE THREAD

**Issue by fursphere** [prusa3d/Prusa-Firmware-Buddy#4224] opened 2024-09-27 15:19 UTC
### Printer model

XL 5 tool

### Firmware version

6.2.0-alpha1 Firmware

### Upgrades and modifications

None

### Printing from...

USB / PrusaConnect

### Describe the bug

After upgrading XL 5 toolhead to 6.2.0-alpha1 Firmware (in an attempt to address a tool docking issue due to new CoreXY features), Wifi no longer works.  Constant connect/disconnect.  It'll pull an IP from DHCP, and look like its connected, then a few minutes later disconnect.    Never sync's back up with PrusaConnect.

Tried reseting wifi credentials, switching to Eth0 then back to Wifi, no fix.

### How to reproduce

Upgrade printer to [6.2.0-alpha1 Firmware]

### Expected behavior

Wifi connection should work; Printer should connect to PrusaConnect

**Comment by CZDanol** [comment] 2024-09-27 15:24
Duplicate of #4199

**Closed by CZDanol** 2024-09-27 15:24 UTC
Labels: bug
