### ISSUE TITLE
[BUG} Octoprint doesn't give printer status on LCD

### ISSUE THREAD

**Issue by srjacob999** [prusa3d/Prusa-Firmware-Buddy#3410] opened 2023-10-27 12:56 UTC
Printer type MK4
Printer firmware version - 5.00
MMU upgrade - No MMU
MMU upgrade firmware version - NO MMU

** USB/Octoprint**

Describe the bug
When using the MK4 with Octoprint, the printer status and job times do not appear on the printer LCD

To Reproduce
Run the printer with Octoprint

Expected behavior
Print status should appear on the LCD screen

G-code
Any print

Video
None

**Comment by jdfalk** [comment] 2023-10-27 19:06
This is probably a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/189

**Comment by dandrzejewski** [comment] 2023-11-12 17:10
Could also be related to #1497.

**Comment by srjacob999** [comment] 2023-11-12 17:20
No.  That relates to the 8 bit firmware on the Mini.

**Comment by danopernis** [comment] 2024-06-03 07:10
Duplicates https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/189

**Closed by danopernis** 2024-06-03 07:10 UTC
Labels: bug, duplicate
