### ISSUE TITLE
[BUG] XL Prusa Link throws error "Not a GCODE" when trying to upload a bgcode

### ISSUE THREAD

**Issue by RichiH** [prusa3d/Prusa-Firmware-Buddy#3431] opened 2023-11-01 12:11 UTC
**Printer type** - XL
**Printer firmware version** - v5.1.0-alpha2
**Slicer** PrusaSlicer-2.7.0-alpha1+linux-x64-GTK3-202310191626
**Original or Custom firmware** - Original
**Optional upgrades** - n/a
**USB drive or USB/Octoprint** USB drive

**Describe the bug**
When trying to upload a bgcode called `RadioLab_Taung_Child_Skull_via_shootdigital_2014.05.26__repaired_mm__0.6n_0.15mm_PLA_XL_10h5m.bgcode` I get the error:
![image](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/754723/61959c13-6c9a-414c-a440-c758a768eaf2) in PrusaSlicer.

Renaming the file to `RadioLab_Taung_Child_Skull.bgcode` before uploading works.

**Comment by c10l** [comment] 2023-11-10 18:34
Same but on a MK3.9. Couldn't find a file name that it would find acceptable though.

**Comment by Crowlord** [comment] 2023-11-27 20:29
I suspect this is a file length issue. Shortening the file fixes it for me.

**Comment by RalphBacon** [comment] 2024-02-15 09:57
This is a regression bug. It used to work. It rejects this filename:
Weloc-Style Hinge #2-Body Outer Arm [2024_2_15 9.52] (52m).gcode

but previously accepted the following, longer file name:
Weloc-Style Hinge #2-Body Outer Arm_0.4n_0.2mm_PLA_MINI_3h30m.gcode

which is a problem for me as I can no longer print previously sliced items unless I change the file name in Windows first.

Running Mini+ with latest firmware and slicer too (as @ 15 Feb 2023)

**Comment by RalphBacon** [comment] 2024-06-04 06:44
Perhaps someone from Prusa Support would like to comment before this is auto-closed as stale? Has it been fixed/won't fix?

**Comment by techogre** [comment] 2024-07-21 19:19
Having the same issue with my XL with firmware 6.0.4.

**Comment by danopernis** [comment] 2024-07-22 08:45
@techogre I tried to create some binary gcode and use your filename. Uploading using PrusaLink went OK without any error. Did you upload to the root directory, or into some subdirectory on the USB drive? When uploading to the sufficiently nested subdirectory structure I am getting `414: URI Too Long`. What is the exact error message you are getting? Is it `415 Unsupported media type` a.k.a. `Not a GCODE`? That would indicate some truncation of the filename.

**Comment by danopernis** [comment] 2024-08-20 13:06
Let me close this as a duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3039

**Closed by danopernis** 2024-08-20 13:06 UTC
Labels: bug
