### ISSUE TITLE
[BUG] wrong end time on the printer display 

### ISSUE THREAD

**Issue by jbriard** [prusa3d/Prusa-Firmware-Buddy#828] opened 2020-08-21 17:29 UTC
**Printer type** - Prusa Mini
**Printer firmware version**-  4.2.0

**SD card or USB/Octoprint** - SD card

**Describe the bug**
 The end time is different from the web interface and the physical display.
The display show a wrong time.
  
![prusa-bug](https://user-images.githubusercontent.com/10330057/90500113-bc3a7a80-e14a-11ea-9f77-74c4fdef589a.png)
![IMG_20200818_115442](https://user-images.githubusercontent.com/10330057/90500146-c78da600-e14a-11ea-9682-a4992f71194a.jpg)

**To Reproduce**
  Just launch a print
  
**Expected behavior**file:///home/enky/Pictures/prusa-bug.png

  Having the same and right time in both interface.

**Comment by dtackgrounded** [comment] 2020-08-24 23:16
I'm also seeing different end times; firmware 4.2.0.
Is there anyway to temporarily reset to estimated time remaining instead of wall clock end time?

**Comment by adynis** [comment] 2020-08-24 23:26
yes: unplug lan cable 😊 (probably before printer is started...)

**Comment by JohnnyDeer** [comment] 2020-08-25 05:24
Hi, this issue is duplicate of #708. I´m closing this one.

**Closed by JohnnyDeer** 2020-08-25 05:24 UTC
Labels: bug
