### ISSUE TITLE
[BUG] Manual Axis Movement Problem - Extruder caught in infinite movement loop

### ISSUE THREAD

**Issue by DRKMSTR** [prusa3d/Prusa-Firmware-Buddy#1015] opened 2020-11-01 18:17 UTC
**Printer type** - MINI

**Printer firmware version**-  4.2.1

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint** - USB Drive

**Describe the bug**

I preheated the bed and moved the "E" axis (extruder) by 15mm, to clear out all the old tempered filament from a bunch of preheat cycles. After about 5 minutes, it was still extruding filament and I had to manually restart the printer to stop it.

**How to reproduce**

Unsure, I did not want to reproduce it as it was a pretty unnerving result, it would blob the entire hotend if I wasn't paying attention. It was preheated to PETG, then the "E" axis was told to manually move 15mm (or whatever to the soft limit (where you can't scroll any more), then a few mm more as it extruded)

**Expected behavior**

I expected it to extrude for a minute, maybe two to clear out the old tempered filament.

**G-code**

N/A

**Crash dump file**

N/A

**Video**

N/A

**Comment by JohnnyDeer** [comment] 2020-11-18 10:03
Hi @DRKMSTR unfortunately we are not able to reproduce it. Please wait till new FW will be released and try to reproduce this issue. Thank you.

**Comment by JohnnyDeer** [comment] 2020-12-15 10:22
@DRKMSTR 4.3.0-RC1 is out could you please try it?

**Comment by DRKMSTR** [comment] 2020-12-15 14:27
> @DRKMSTR 4.3.0-RC1 is out could you please try it?

Will do as soon as I get some time. 

I need to install the new probe and a plated copper nozzle first.

**Comment by JohnnyDeer** [comment] 2021-02-17 12:54
@DRKMSTR is this problem still actual?

**Comment by JohnnyDeer** [comment] 2021-05-13 11:34
I'm closing this issue because of no response.

**Closed by JohnnyDeer** 2021-05-13 11:34 UTC
Labels: bug
