### ISSUE TITLE
[ENHANCEMENT] Show time remaining when Mini has a prusalink attached

### ISSUE THREAD

**Issue by markdesouza** [prusa3d/Prusa-Firmware-Buddy#3031] opened 2023-03-12 09:50 UTC
Enter what type of printer or upgrade the enhancement applies to.
Prusa Mini+
ESP8266 for Prusalink

**Is your suggested improvement related to an existing problem? Please describe.**
On the Prusa's lcd screen when a PrusaLink device is attached, it only states the time as in hh:mm remaining, presumably because the device has an ntp feed.

**Describe the expected functionality**
It would be nice if the lcd still also displayed the number of minutes remaining as sometimes you want to know if its 10mins or 20mins away without having to look at your watch and do subtraction...

**Comment by Prusa-Support** [comment] 2023-04-26 15:50
Thanks for getting in touch.

The current expected behavior is that the printer will show the _estimated end time_ instead of the _remaining time_ when connected to the router.

This was already happening before, since the introduction of _Prusa Connect Local_ (obsolete version of _Prusa Link_).
The issue is not directly related to Prusa Link. Basically, it was already happening with older firmware versions anytime the printer was connected to the network via Ethernet. 

This issue should be closed as duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/648.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-04-26 15:50 UTC
Labels: enhancement
