### ISSUE TITLE
[BUG] <XL Multihead temps Head1 with no reason>

### ISSUE THREAD

**Issue by Sebbo69** [prusa3d/Prusa-Firmware-Buddy#3693] opened 2024-01-19 15:09 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI, MK4, XL]
XL 5Tools

**Printer firmware version** - [e.g. 4.0.5, ...]
5.1.2
**Original or Custom firmware** - [Original/Custom]
original
**Optional upgrades** - [e.g. Filament Runout Sensor]

**USB drive or USB/Octoprint**
  Please let us know if you print via USB flash drive or USB/Octoprint
PrusaConnect from PrusaSlicer

**Describe the bug**
When i start a print with Head 5, Head 1 is heating up. The complete print is the Head on full temperature.

**How to reproduce**
  Please describe steps to reproduce the behavior.

**Expected behavior**

**G-code**
  Please attach the G-code you had trouble with. This will make it easier for us to replicate the error.

**Crash dump file**
  Please send the crash dump file to Prusa by emailing it to reports@prusa3d.com. Sharing this file is important and helps us investigate the bug.

  Do not share the file publicly, as the crash dump contains a raw snapshot of the printer's memory and may include unencrypted sensitive information.

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by Sebbo69** [comment] 2024-01-19 17:25
Now I see the problem in the slicer. but no idea where it comes from. Very little is printed by the first extruder. If extruder 5 is selected then it will not take the first one out of park position at all. But heat it up anyway.

<img width="419" alt="Bildschirmfoto 2024-01-19 um 18 18 37" src="https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/49972319/d7a33876-7ca3-4a78-891a-111cb98b21ad">

**Comment by bkerler** [comment] 2024-01-21 19:29
Please write an issue in PrusaSlicer, as it seems to be related with the slicer.

**Comment by Sebbo69** [comment] 2024-01-21 19:30
Okay...

**Comment by bkerler** [comment] 2024-01-21 21:55
Duplicate of #3669. I couldn't see an issue on the firmware implementation, but not 100% sure yet. It's best to go for the PrusaSlicer issue first, as it is most likely gcode generation related.

**Comment by TechnoSwiss** [comment] 2024-01-22 05:08
This isn't just an issue with Prusa slicer, although it IS related to how it's sliced, it might be caused by the same bug as #3669 but could still be it's own issue.

I keep running into this when I slice a model using the "default" toolhead in PrusaSlicer, and then when I print from the front panel I switch out for a different toolhead. It seems like the firmware doesn't quite translate everything over from the default toolhead to whatever was changed to at print-time.

**Comment by Sebbo69** [comment] 2024-01-24 15:27
Problem was my mistake. Printed with wrong profile in slicer. I used the 1 Tool profile and added more extruder.
But now I use the 5Head profile in Prusaslicer and it works

**Closed** 2024-06-11 11:36 UTC
Labels: bug
