### ISSUE TITLE
[ENHANCEMENT] Prusa Link should allow uploads of firmware files over the local network

### ISSUE THREAD

**Issue by cnlson** [prusa3d/Prusa-Firmware-Buddy#4183] opened 2024-09-06 04:47 UTC
### Printer model

mk3.5

### Describe the enhancement

It would be nice rather than having to sneakernet the firmware files if they could be just uploaded over prusalink. Prusalink will now upload them only to fail to save at the end and state the file is not a gcode or bgcode

### Expected functionality

firmware bbf files should be supported to upload via prusalink

**Comment by danopernis** [comment] 2024-09-06 07:09
This seems to be a duplicate of #4099

**Closed by danopernis** 2024-09-06 07:09 UTC
Labels: enhancement
