### ISSUE TITLE
[BUG] Filament sensor fails to pause OctoPrint

### ISSUE THREAD

**Issue by BerenV** [prusa3d/Prusa-Firmware-Buddy#1030] opened 2020-11-04 01:38 UTC
**Printer type** - MINI

**Printer firmware version**-  4.2.0

**Original or Custom firmware** Original

**Optional upgrades** - Filament Runout Sensor

**USB drive or USB/Octoprint** - Octoprint

**Describe the bug**
 I just had a relatively long print get ruined by a failure of the printer to pause when it ran out of filament. I have the sensor installed and enabled, it is reading the state correctly but it didn't pause Octoprint

**How to reproduce**
Try printing a longer print in Octoprint and cutting the filament I guess...
  
**Expected behavior**
  The printer should pause when it runs out of filament!

Anyway, I'm updating my firmware to 4.2.1 but I didn't see anything about this in the release notes. It would be awesome if this could be fixed but for now I guess my filament sensor won't be doing me any good since I print almost exclusively over Octoprint. I've also had a print (luckily a smaller one) fail to pause and initiate the color change two times. However, I've also had it work just fine so I'm not sure what to think. I'm using PrusaSlicer and mostly stock profiles.

![IMG_6574](https://user-images.githubusercontent.com/9524062/98059167-f2ef6b00-1df2-11eb-830f-1410dc4c3afd.JPG)

Thanks!

**Comment by JohnnyDeer** [comment] 2020-11-04 08:17
Hi @BerenV this is duplicate of #739. I close this issue.

**Closed by JohnnyDeer** 2020-11-04 08:17 UTC
Labels: bug

**Comment by BerenV** [comment] 2020-11-04 08:19
Ok thanks!
