### ISSUE TITLE
[BUG] MK4 5.0.0 filament change requested mid print

### ISSUE THREAD

**Issue by oh2gqc** [prusa3d/Prusa-Firmware-Buddy#3293] opened 2023-09-21 13:42 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MK4]

**Printer firmware version** - [5.0.0]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [None]

**USB drive or USB/Octoprint** [USB flash drive]

**Describe the bug**
While printing printer parked the hotend and requested a filament change.
After removing & inserting the same filament again, the print continued.
There are no filament change commands in the g-code file.
G-code was created by PrusaSlicer 2.6.1
[gcode.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12685280/gcode.zip)

**Expected behavior**
Print from start to end without filament changes.

**G-code**
 Attached

**Crash dump file**
No crash, print finished normally.

**Comment by murk-sy** [comment] 2023-09-21 16:04
Duplicate of #3129
Title is different but it is related to the same issue

**Closed** 2024-05-30 14:40 UTC
Labels: bug, duplicate
