### ISSUE TITLE
[ENHANCEMENT]Move the print head up after first layer calibration

### ISSUE THREAD

**Issue by ftrofin** [prusa3d/Prusa-Firmware-Buddy#1041] opened 2020-11-10 06:20 UTC
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - MINI
**Optional upgrades** - Filament Runout Sensor

**Is your suggested improvement related to an existing problem? Please describe.**
When I do the first layer calibration, at the end, the head moves to the right but stays low so when I am asked if I want to repeat it I can't take the print plate out for closer inspection. Worse, if I say yes to the question (I want to repeat the calibration) I am prompted to clean the plate. How am I supposed to clean the plate if the head is a few centimeters away from the plate?

**Describe the expected functionality**
 Move the print head up on the Z axis so I can take out the plate to inspect it and clean it if I want to repeat the test.

**Comment by JohnnyDeer** [comment] 2020-11-10 07:52
Hi @ftrofin this is duplicate of #242 so i close this issue.

**Closed by JohnnyDeer** 2020-11-10 07:52 UTC
Labels: enhancement
