### ISSUE TITLE
[BUG] WebUI: folders on USB not accessible

### ISSUE THREAD

**Issue by Rich-I** [prusa3d/Prusa-Firmware-Buddy#2915] opened 2023-01-11 08:58 UTC
**Printer type** - [MINI]

**Printer firmware version** - [ 4.4.1-RC1-4188]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive**
  Printing via USB flash drive, and connected via network

**Describe the bug**
When organizing gcode-files on the USB flash drive in different folders, only root folder can be accessed via WebUI

**How to reproduce**
Add folders on original MINI USB flash drive on a PC (eg linux - OpenSuse 15.3), put G-code files in newly created folder.
With USB flash drive inserted in the MINI, files and folders are accessible through the user interface on the MINI.
When accessing the MINI over the network, only the files in the original root folder are listed. Also when uploading files, only the root folder is accessible.

**Expected behavior**
When viewing the storage tab in the WebUI, it is expected to see also the folders on the USB flash drive so it is possible to access other folders to store data files for printing

**Comment by Prusa-Support** [comment] 2023-02-04 15:26
Thanks for reaching us.

This is a duplicate of issue https://github.com/prusa3d/Prusa-Link-Web/issues/290, in the relevant repository.
Also, this is not a bug but a planned feature, yet to be implemented.

This issue will be linked through the mention and closed as a duplicate.

Michele Moramarco
Prusa Resarch

**Closed by Prusa-Support** 2023-02-04 15:26 UTC
Labels: in progress
