### ISSUE TITLE
[BUG] Preheat only goes to 170 °C nozzle temp

### ISSUE THREAD

**Issue by ulab** [prusa3d/Prusa-Firmware-Buddy#3074] opened 2023-05-10 07:51 UTC
**Printer type** - MK4 (Mini too)
**Printer firmware version** - 4.6.1
**Original or Custom firmware** - Original
**Optional upgrades** - 
**USB drive or USB/Octoprint** - irrelevant

**Describe the bug**
After selecting a preheat temperature in the menu, the nozzle temperature only heats up to 170°C, with the target temperature being shown at the correct value.

**How to reproduce**
Select `Preheat`, `PETG` and watch the temperature. It blinks red while heating to 170°C and then goes green around 170°C, showing 170/230°C

**Expected behavior**
I'd expect the nozzle to heat up to the chosen temperature.

**Comment by BootsSiR** [comment] 2023-05-12 00:42
@ulab 170C is the temperature at which the printer will do it's bed levelling routines.  It will then heat to the selected temperature prior to starting the print.  If you preheated to 230C and started a print, the printer would have to wait for the nozzle to cool to 170C before proceeding.

**Comment by ulab** [comment] 2023-05-12 06:03
Yes. But if I explicitely select to preheat to 230C, I want it to do that. Otherwise I'd chose to preheat to 170C.

I may want to push some cleaning filament through the hotend, hot-tighten the nozzle or something else and not turn the knob forever in the Settings menu.

If Preheat let's me chose 230C and then just heats up to 170C, it's irritating. Especially if it shows 170/230C, but just doesn't heat up anymore even though the target temperature of 230C has not been reached.

**Comment by BootsSiR** [comment] 2023-05-12 10:05
In your case I'd just set the nozzle temperature to 230C in the control menu.  Preheat seems to be intended to preheat for a print.

**Comment by murk-sy** [comment] 2023-05-15 09:02
It's not really a bug, but it is definitely confusing if you don't already know exactly what the function does.

I've made a feature request #1795 that should cover this (since it adds a function + clarifies what it does). I'd appreciate your thoughts there.

**Comment by Prusa-Support** [comment] 2023-06-23 19:36
Thanks for writing.

Please select `filament` -> `load`/`unload`/`change`/`purge`.
Alternatively, `settings`-> `temperature` if you have reason to skip the operations of the motor _while heating up_.

The _preheat_ option is actually intended for the preparation of the printer for the print, which would imply noticeable downtime if the nozzle was always reaching the target only to cool down before the _mesh bed leveling_.
All in all, this is not a bug; on the contrary, this is intentional.

Could the issue be closed?

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment] 2023-07-14 11:29
Thank you again for your input and I hope you are satisfied with the answer.
It seems safe to close this issue now.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-07-14 11:29 UTC
Labels: awaiting response

**Comment by stephen304** [comment] 2026-08-09 18:41
Just found this thread after being confused coming from my mk3s+ to the mk4. What I don't understand is, what is the point of having different preheat settings if they all just preheat to 170? The gcode will already set the starting temp for the filament it's sliced for, so it seems like a waste of space to have options for all filaments instead of just having a generic preheat to 170 option. I use preheat so I can manually push filament through the nozzle, and being able to select the different temperatures in the preheat menu was very convenient. Now it seems like all of them do the same thing. With this new behavior, why does it matter if I select PLA preheat and then print a PETG gcode since it will preheat to 170 and then heat up to 120 when it starts the gcode?

If you are dead set on making them all preheat to 170 then I feel like all the options aren't doing much. I've long wanted an actual partial pre-heat option separate from the full pre-heat to final temp on my mk3s, and I think having the ability to quickly have both options in the pre-heat menu is a vastly better experience than making people scroll through temperatures manually in the control/temp menu.

And sure, you can go to move axis and trigger a full pre-heat by moving E axis, but then I need to go back and disable steppers so I can push filament. It feels like my printer is working against me.
