### ISSUE TITLE
[BUG] Stuck FIlament Detected with MMU3

### ISSUE THREAD

**Issue by geekcouplettv** [prusa3d/Prusa-Firmware-Buddy#4110] opened 2024-07-30 21:00 UTC
### Printer model

MK4 + MMU3

### Firmware version

6.0.4

### Upgrades and modifications

Duckt fan

### Printing from...

Prusa Connect

### Describe the bug

Random interupts with Stuck Filament detection

### How to reproduce

Start print and after few or couple minutes stops print becuase of Stuck Filament Detection. The issue started to happen after update from 6.0.2 firmware. The Issue is happening on PLA / PETG filaments

This issue was report by other users also on forum : https://forum.prusa3d.com/forum/original-prusa-xl-tool-changer-hardware-firmware-and-software-help/stuck-filament-detection-causing-filament-to-get-stuck/#post-717652

I even changed few nozzles but no luck. People say it is firmware bug and on 6.0.1 is working everything verry well.

**Comment by danopernis** [comment] 2024-08-06 10:17
This looks like a duplicate of #4086

**Closed** 2024-08-12 06:40 UTC
Labels: bug, duplicate
