### ISSUE TITLE
[QUESTION] Build failed EEPROM_SETTINGS enabled. Why?

### ISSUE THREAD

**Issue by PeterDHabermehl** [prusa3d/Prusa-Firmware-Buddy#808] opened 2020-08-17 15:34 UTC
When I add "#define EEPROM_SETTINGS" to config_a3ides2209_02.h the build fails.

I urgently need M500 to set the E-Steps for Bondtech extruder and PID tuning for the Bondtech heatbreak. Willing to break the appendix since I'm forced to do so, BUT please help me build my firmware with M500 enabled.

Unfortunately the build script does not indicate WHY it fails with EEPROM_SETTINGS enabled...

**Comment by JohnnyDeer** [comment] 2020-08-18 06:26
Hi @PeterDHabermehl, this issue is duplicate of #767. I´m closing this one.

**Closed by JohnnyDeer** 2020-08-18 06:26 UTC
Labels: question
