### ISSUE TITLE
[BFW-5764] [BUG] XL: Slow homing (from corner to probe point) after print

### ISSUE THREAD

**Issue by Racemade** [prusa3d/Prusa-Firmware-Buddy#4040] opened 2024-06-11 17:00 UTC
### Printer model

XL

### Firmware version

6.0.3 Official Release

### Printing from...

Prusa Connect

### Describe the bug

After a successful print, the printer does not work properly.
If you go back to the start menu und press Auto Home, the motors are louder then normal and (thats the most important thing) the printer does a very, very slow auto home.

You have do restart the XL. Then it will perform as it should.

### How to reproduce

Print something.
Go back to menu.
Do an Auto Home

### Expected behavior

If i click Auto Home the printer should do it as always - silent and fast.

**Comment by Racemade** [comment] 2024-06-27 07:31
Still exists in 6.0.3 and after a full factory reset.

**Comment by danopernis** [comment] 2024-06-27 14:49
I managed to reproduce this. Doesn't seem like a big issue w.r.t. homing, because the distance the nozzle needs to travel to get from the corner to the probing point isn't that large. However, it may indicate some other underlying issue so it is worth further investigation. I am opening internal ticket for that.

**Comment by Racemade** [comment] 2024-07-03 08:35
https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/168211087/40d97ba6-50cd-40d1-a473-33eb3f0cc34b

Thats slow...auto home After Print. There is a bug or something else.

**Comment by Racemade** [comment] 2024-07-19 17:14
Any news here? Or anybody else with this kind of problem?

**Comment by clefranc** [comment] 2024-07-30 16:13
Same here with 6.0.4+14924

**Comment by Racemade** [comment] 2024-09-08 20:12
Still exists in 6.1.3

**Comment by danopernis** [comment] 2024-09-17 08:07
This should be fixed in 6.2.0-alpha1 according to the internal ticket. It somehow didn't make it to the release notes. Can you test it? Or wait a bit for stable 6.2.0 if you don't want to use alpha firmware (which has some regression w.r.t. to Wi-Fi)

**Comment by Racemade** [comment] 2024-10-05 07:55
I wait for the official release- thank you for comment!

**Comment by Racemade** [comment] 2024-11-13 11:30
So for now 6.2.0 alpha 2 resolved the issue. Waiting now for the official release and we will see.
Thanks!

**Closed** 2024-11-13 11:30 UTC
Labels: bug, scheduled
