### ISSUE TITLE
[BUG] Mini+ BSOD precise_stepping

### ISSUE THREAD

**Issue by Sfas19** [prusa3d/Prusa-Firmware-Buddy#3322] opened 2023-09-26 19:53 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI+]

**Printer firmware version** - [5.1.0-alpha]

**Original or Custom firmware** - [Original]

**Optional upgrades** - [Filament Runout Sensor]

**USB drive or USB/Octoprint**
  USB drive (gcode transferred directly from prusaslicer)

**Describe the bug**
  Near the end of my print (2 hours) the printer crashes with a BSOD with the note "Precise_stepping.cp"
  The print was with clear PETG with 100% infill. A second attempt resulted in the same issue.
![20230926_100410](https://github.com/prusa3d/Prusa-Firmware-Buddy/assets/35080721/33e3a43c-f284-453d-8141-e8bbc57fdfe9)

**How to reproduce**
  Did not print yet with another file/material. Earlier (longer and shorter) prints with the same material and settings did not have this issue. Major difference in models is that this file (with the error) had a small top area.

**Expected behavior**
  Not to crash

**G-code**
  G-code can be found in the zip file, together with the crash dump file
[precise_stepping BSOD.zip](https://github.com/prusa3d/Prusa-Firmware-Buddy/files/12731376/precise_stepping.BSOD.zip)

**Crash dump file**
  See above mentioned zip file

**Video**
  Please attach a video. It usually helps to solve the problem.

**Comment by darraghbr** [comment] 2023-09-27 02:45
Is this a duplicate of #3288 ?

**Comment by Sfas19** [comment] 2023-09-27 03:13
Sorry, indeed looks like the same error.

**Closed** 2023-12-17 06:57 UTC
Labels: bug
