### ISSUE TITLE
[ENHANCEMENT] Changing the filament, unnecessary heating of the bed

### ISSUE THREAD

**Issue by eWuPi** [prusa3d/Prusa-Firmware-Buddy#3015] opened 2023-03-02 14:55 UTC
Enter what type of printer or upgrade the enhancement applies to.
**Printer type** - [MINI]

**Is your suggested improvement related to an existing problem? Please describe.**
Changing the filament, unnecessary heating of the bed

**Describe the expected functionality**
It is not necessary to turn on the heating of the bed when changing the filament. In addition, a sound signal would be useful just before the filament ejects, so that you do not have to wait at the printer for the nozzle to heat up.

**Comment by Prusa-Support** [comment] 2023-04-08 15:10
Thank you for your feedback.
This enhancement has been discussed at length, on several occasions.

I hope you don't mind me closing this issue as duplicate of https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/706.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2023-04-08 15:10 UTC
Labels: enhancement
