### ISSUE TITLE
Bluescreen connection Octoprint

### ISSUE THREAD

**Issue by rainer1146** [prusa3d/Prusa-Firmware-Buddy#1415] opened 2021-05-13 14:54 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - [MINI]

**Printer firmware version**-  [4.2.3. Beta]

**Original or Custom firmware** [Original]

**Optional upgrades** - [Filament Runout Sensor]

**Octoprint**

I can start the Mini even if it is connected to a Raspberry with Octoprint.
He works completely normally.
Only when I go to connect in Octoprint does the Mini restart and end with a blue screen

**Comment by JohnnyDeer** [comment] 2021-05-17 06:20
Hi @rainer1146, this issue is duplicate of #1351 and will be fixed soon. I´m closing this issue.

**Closed by JohnnyDeer** 2021-05-17 06:20 UTC
Labels: bug
