### ISSUE TITLE
[Bug] Reopening: Remote printing w/ Octoprint - filament change not working

### ISSUE THREAD

**Issue by ifekali** [prusa3d/Prusa-Firmware-Buddy#626] opened 2020-06-25 10:10 UTC
This issue (#362) was closed prematurely, I am reopening it here as follows:

> Further to issue #360 during remote printing when the printer reaches the M600 command in GCODE
> extruder pulls out the filament and waits for user input (a.k.a. continue when the new filament is loaded).
> 
> So, while doing that, when the new filament is loaded and I press continue, the printer comes back to the remote printing > screen without loading the filament. Funny thing is it doesn't come back to print either.
>
> Prusa mini FW version 4.0.5, Prusa slicer 2.2.0

This is still an issue with 4.1.0-RC1 firmware, confirmed by at least two other users.

**Original Prusa Mini** 
**4.1.0-RC1 firmware**

**Comment by deltwalrus** [comment] 2020-06-26 14:14
Confirm this is still an issue with 4.1.0-RC1

**Comment by Chleba** [comment] 2020-07-09 22:58
This bug have been fixed in v.4.1.0 final version.

**Comment by twobit0** [comment] 2022-11-07 05:13
This is still an issue in 4.3.4!!! can we reopen this?

**Comment by Prusa-Support** [comment] 2022-11-25 13:02
I'm sorry for the confusion.

Because it is confirmed that the issue showed up again, I will actually close this one as a duplicate and reopen https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/362.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2022-11-25 13:02 UTC
Labels: bug
