### ISSUE TITLE
[QUESTION] XL LED Strips dim after a few minutes. Why? And will RGB be enabled at some point?

### ISSUE THREAD

**Issue by hatesyourface** [prusa3d/Prusa-Firmware-Buddy#3225] opened 2023-08-25 16:30 UTC
Why do the LED strips dim, and why isnt it controllable? Also, in the demos they are RGB strips. Are these RGB, and if so will colors be unlocked at some point?

**Comment by ulab** [comment] 2023-08-26 14:14
I can confirm they are RGB, because when the XL detects a crash, they turn red. :-)

**Comment by rcmaniac25** [comment] 2023-09-06 04:35
They do seem to know about it given the comment: https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/master/include/leds/side_strip_control.hpp#L14

**Comment by Prusa-Support** [comment] 2023-09-19 22:45
Thanks for your suggestion.

Some sort of customization should be possible in the future.
Also, this issue partially duplicates https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3118.

Michele Moramarco
Prusa Research

**Comment by hatesyourface** [comment] 2023-09-20 03:26
Michele, is it intentional that the light strips dim at 120 seconds even when printing?

**Comment by Prusa-Support** [comment] 2023-10-11 22:20
Yes. I don't know the ultimate reason why it is so but it is intentional indeed.
I'm not sure how long it takes to dim out exactly either but it may take a couple of minutes.
However, I seem to understand that the behavior may change in various circumstances.
Unfortunately, I don't have access to specific information at the moment but the described behavior is expected.

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment] 2024-03-30 10:52
Light strips dimming can be disabled in FW 6.0.0 which is currently available for _alpha_ testing.
https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v6.0.0-alpha

Michele Moramarco
Prusa Research

**Comment by Prusa-Support** [comment] 2024-04-26 16:44
The final release 6.0.0 is out and strip light dimming can be disabled with it.
https://github.com/prusa3d/Prusa-Firmware-Buddy/releases/tag/v6.0.0-xl

This issue will be closed as solved now.

Michele Moramarco
Prusa Research

**Closed by Prusa-Support** 2024-04-26 16:44 UTC
Labels: question, UI, XL
