### ISSUE TITLE
[BUG] Live Adj (Z Offset) is not saved between reboots for Octoprint mode

### ISSUE THREAD

**Issue by derenma** [prusa3d/Prusa-Firmware-Buddy#586] opened 2020-06-17 08:20 UTC
**Printer type** - [MINI]

**Printer firmware version**-  4.0.5

**Original or Custom firmware** - Original

**Optional upgrades** - Filament Runout Sensor, Bondtech Extruder, Raspberry Pi w/ OctoPrint

**USB drive or USB/Octoprint** - USB/Octoprint

**Describe the bug** - Live Adj resets to 0.000 after reboot. (Sure, I could set the Z offset manually with G-Code, but unsure if there is custom G-Code that will set Level Adj directly.)

**How to reproduce** - Reboot after setting Live Adj in OctoPrint mode.

**Expected behavior** - Live Adj returns to previous setting after a reboot of the printer.

**G-code** - N/A

**Crash dump file** - N/A, Not possible.

**Comment by derenma** [comment] 2020-06-21 05:38
As of version 4.1.0-RC1, Live Adjust is also not saved between Octoprint connect/disconnect/connect cycle. It's slightly different issue, but probably has the same root cause.

**Comment by EBD232** [comment] 2020-07-24 11:06
I had the problem that Live Adjust would always reset to zero when connecting OctoPrint, and in my case it was caused by the OctoPrint plugin EEPROM Marlin Editor. It sends an M501 (Load all saved settings from EEPROM) when connecting, and that resets Live Adjust to 0. I guess it has to do with the new EEPROM implementation in 4.0.5, I didn't fully understand how it is supposed to work. It might still be a bug if M501 resets the Z offset, even though support for Marlin EEPROM is disabled?

**Comment by jakubmirejovsky** [comment] 2020-11-09 17:36
Video for reference: https://www.youtube.com/watch?v=mjnIPwOg624

**Comment by JohnnyDeer** [comment] 2020-12-16 10:40
@derenma this bug is fixed in 4.3.0-RC1 works well when I reproduce it. To be sure, please try it as well and confirm, thank you.

**Comment by derenma** [comment] 2020-12-20 19:01
@JohnnyDeer I have some time today to test, so thanks for the mention!

**Comment by JohnnyDeer** [comment] 2021-02-10 09:50
@derenma 4.3.0 final is already out :) Did you tried it? Would you update this issue please?

**Comment by derenma** [comment] 2021-02-11 00:08
@JohnnyDeer Sweet! I'll get everything tested soon.

**Comment by JohnnyDeer** [comment] 2021-05-06 08:58
I´m closing this issue as solved and stale.

**Closed by JohnnyDeer** 2021-05-06 08:58 UTC
Labels: bug, octoprint
