### ISSUE TITLE
Out of memory issue while idle (malloc: out of memory)

### ISSUE THREAD

**Issue by MrTrick** [prusa3d/Prusa-Firmware-Buddy#3105] opened 2023-04-17 21:51 UTC
I don't have the exact "steps to reproduce" here, but as best as I remember:

1. The printer was left on for about 1 week. (Prusa Mini+ with the wifi add-on board)
2. Maybe 3-4 prints had been sent to it via wifi during that time, printing for a small percentage of the total uptime.
3. When finished printing, I run the "unload filament" sequence.
4. The printer had been left alone for at least 24 hours prior to the crash.

<img src="https://user-images.githubusercontent.com/127012/232617882-7d2009af-1356-489e-bc93-400dacef5d84.png" width="50%"/>
<img src="https://user-images.githubusercontent.com/127012/232617914-75de47ca-3d33-4dce-8bf9-5d30809ae148.png" width="50%"/>

**Comment by Prusa-Support** [comment] 2023-06-16 08:33
Hello, thank you for the report and sorry for the late response. We are aware of some possible causes: 
- It might happen when the browser is closed accidentally - in that case, the solution would be logging in again in Prusa Link and clicking on "storage"
- It might happen when the webpage is refreshing a few times "at a fast rate", like refreshing "a few times in a row".
- A long operation session might also be behind it

Is there a specific sequence of actions that you might have found causing the issue? In the sense, would it be reproducible with some specific sequence of actions? 

I'll close this particular thread being this a duplicate of some others, including #2802, in case of anything feel free to comment on that thread.

**Closed by Prusa-Support** 2023-06-16 08:33 UTC

**Comment by MrTrick** [comment] 2023-06-21 09:38
Thanks! I'm not aware of any actions or ways to reproduce it, and hasn't happened a second time yet. I'll keep an eye out.

**Comment by globaltommy** [comment] 2023-08-18 17:50
Just happened to me half way through the print.
I think it happened because I woke up my computer that has had the Prusa Link website opened. As soon as I woke up the PC the printer crashed.

I hope this helps
