### ISSUE TITLE
[BUG] MK4 gets stuck on "remove filament" display during printing; reset required

### ISSUE THREAD

**Issue by neuron-whisperer** [prusa3d/Prusa-Firmware-Buddy#3990] opened 2024-05-09 18:30 UTC
Please, before you create a new bug report, please make sure you searched in open and closed issues and couldn't find anything that matches.

**Printer type** - MK4 built from kit

**Printer firmware version** - 6.0

**Original or Custom firmware** - Original

**Optional upgrades** - None

**USB drive or USB/Octoprint** - USB

**Describe the bug**

While changing filament mid-print, the MK4 reverses the extruder motor and then displays a screen reading: "Was the filament ejected?" If "yes" is selected, the MK4 asks the user to remove the plug of filament from the extruder, and will not advance until the filament sensor detects that it is removed.

If this step cannot be performed - e.g., "yes" was accidentally selected, or the filament sensor is malfunctioning - the printer remains on this screen with no options to return to the previous step, cancel, skip the detection, etc. The only option at this stage is to reset the printer (causing any mid-course print to fail).

Also, resetting the printer at this stage may cause a kernel panic.

**How to reproduce**

1) Start printing.

2) Invoke a filament change during the print (either with a Gcode instruction or using the UI).

3) Wait for the printer to eject the filament and display the question: "Was the filament ejected?" and then select "Yes."

4) Wait for the printer to display the instruction: "Please remove the filament from the extruder," and look for any option to proceed other than removing the filament or resetting the printer. There is no such option.

5) Optionally, hit the Reset button and watch the printer display a kernel panic message, requiring another reset.

**Expected behavior**

The printer should display one or more fallback options: Cancel (abort the filament change), Skip (proceed with trying to load filament in case the filament sensor is malfunctioning), Back (return to the "was the filament ejected?" screen), Abort Print, etc. - so that the user is not stuck on this screen without recourse.

**G-code** - n/a

**Crash dump file** - n/a

**Video** - n/a

**Comment by CZDanol** [comment] 2024-05-23 11:46
Closing as a duplicate of #3129 .

**Closed by CZDanol** 2024-05-23 11:46 UTC
Labels: bug

**Comment by Ludicrous2k** [comment] 2024-10-22 05:11
I found a work around!!!

After you pull out your old filament, stick your new filament in as far as it'll go, and then pull the power cable. Once you plug it back in and and the printer boots up you can then select resume print and it'll start auto feeding the new filament and continue where it left off. LOL

**Comment by TimetravelerDD** [comment] 2025-02-20 09:19
I am sorry, but I have to respectfully disagree with @CZDanol @CZDanol-prusa 
#3129 is about the filament sensor not working correctly 

This issue however is about an issue that will leave the user in an unrecoverable state if he/she accidently pushes the button too early. (not a sensor fault)

This occasionally happens to me too unfortunately and is incredible frustrating, since it really makes the user feel powerless and seems an unnecessary agony that ruins a multi-hour print, that could be easily fixed with a simple back/undo/cancel button. 

I'd appreciate if you can reopen this please @danopernis 
Perhaps it's slightly misclassified as a bug, when it should be labeled as "enhancement"

**Comment by CZDanol** [comment] 2025-02-20 13:02
We are currently implementing a solution for this :)

**Comment by pe0ter** [comment] 2025-02-21 19:42
Hope you have a solution soon as I ran into this bug today on my MK4S running latest firmware.
First time I ran out of filament during print and did not follow the screen too wel so firmware locked up. i did not know I should have forced a power cut to continue printing so I lost 3 hours and had to restart from scratch.

**Comment by siggib007** [comment] 2025-03-14 09:53
I just ran into this just now. Filament ran out like has happened hundreds of time before. I remove the stub and say yes, it was removed fine. Then the printer is stuck on "please remove filament"

**Comment by siggib007** [comment] 2025-03-14 09:59
> I found a work around!!!
> 
> After you pull out your old filament, stick your new filament in as far as it'll go, and then pull the power cable. Once you plug it back in and and the printer boots up you can then select resume print and it'll start auto feeding the new filament and continue where it left off. LOL

This workaround worked for me, Introduce a powerpanic, hold the new filament in extruder when the printer resumes and it starts feeding the new filament.

**Comment by siggib007** [comment] 2025-03-14 10:01
MK4 firmware 6.2.1+8833
