### ISSUE TITLE
[FEATURE REQUEST] Heatbreak fan maximum PWM

### ISSUE THREAD

**Issue by jack-aaron-cooper** [prusa3d/Prusa-Firmware-Buddy#1119] opened 2020-12-03 00:45 UTC
**Printer type** - MINI

**Is your feature request related to an existing problem? Please describe.**
  As a user, I should be able to set the maximum PWM value of the heatbreak fan, so that if I want to use a filament that requires higher temperatures, I will not need to worry as much about filament jams. The current maximum PWM is set to 50%.

https://github.com/prusa3d/Prusa-Firmware-Buddy/blob/95447c177e0d3301713266200ed2620fe10551ae/src/common/config_a3ides2209_02.h#L83

**Describe the expected functionality**
  Have a section in the settings to change the maximum heatbreak fan PWM.

**Comment by blerrgh** [comment] 2020-12-03 04:32
see #997

**Comment by JohnnyDeer** [comment] 2021-02-17 13:17
I´m closing this issue as duplicate of #997.

**Closed by JohnnyDeer** 2021-02-17 13:17 UTC
Labels: feature request
